const I18N = {
    es: {
        nav: { home: "Inicio", projects: "Proyectos", experience: "Experiencia", skills: "Habilidades", contact: "Contacto" },
        hero: { title_prefix: "Hola, soy", subtitle: "Especialista en soporte y administración IT, con experiencia en entornos corporativos y públicos. Gestiono sistemas Linux y Windows, redes, Microsoft 365, hardware y bases de datos, asegurando operaciones estables y eficientes. Me motiva resolver incidencias técnicas y mejorar la experiencia del usuario." },
        cta: { view: "Ver proyectos", cv: "Descargar CV" },
        sections: { exp: "Experiencia", sk: "Habilidades", proj: "Proyectos", contact: "Contacto",
            exp_desc: "HIPRA · My Home Market · Ajuntament",
            sk_desc: "Redes · Cloud · Dev · IA",
            proj_desc: "Snack Tanger · ERAY · Hotel",
            contact_desc: "LinkedIn · Email · GitHub"
        },
        exp: {
            e1_place: "Mayo 2026 - Presente", e1_role: "IT Workplace Technician",
            e1_t1: "IT Procurement (SAP): Gestión de compras de hardware, presupuestos y pruebas PoC (Try and Buy).",
            e1_t2: "Proyectos Industriales: Coordinación del despliegue de infraestructura IT en plantas de producción.",
            e1_t3: "Hardware & Leasing: Administración de flotas Apple/Dell, aprovisionamiento y contratos de leasing.",
            e1_t4: "Salas AV: Gestión de salas de videoconferencia (Cisco Room Bar, Evoko) y migración a MS Teams.",
            e1_t5: "IT Onboarding & Seguridad: Sesiones semanales de bienvenida técnica y buenas prácticas en ciberseguridad.",
            e1_t6: "Operaciones Diarias: Soporte técnico L2 y resolución de tickets corporativos e industriales.",

            e2_place: "Junio 2025 - Mayo 2026", e2_role: "IT Workplace Intern",
            e2_t1: "Soporte L2 & M365: Resolución de incidencias complejas y gestión de usuarios Microsoft 365.",
            e2_t2: "Ticketing & Despliegues: Incidencias en Remedy/SmartIT y preparación de equipos (portátiles, IGEL).",
            e2_t3: "Móviles e Impresión: Configuración de iOS/Android, VoIP Cisco e impresoras RFID/térmicas (Zebra/Honeywell).",
            e2_t4: "Seguridad & Garantías: Coordinación con proveedores de hardware y despliegue de parches de seguridad.",

            e3_place: "Julio 2020 - Junio 2025", e3_role: "Sales Assistant",
            e3_t1: "Atención al Cliente: Asesoramiento personalizado e identificación de necesidades.",
            e3_t2: "Gestión de Stock & Caja: Control de inventario, reposición de productos y operaciones de caja.",

            e4_place: "Noviembre 2023 – Abril 2024", e4_role: "IT Helpdesk Intern",
            e4_t1: "Soporte Municipal: Soporte presencial y remoto a usuarios municipales en hardware, software y red.",
            e4_t2: "Sistemas & Guías: Diagnóstico con herramientas Linux, gestión de permisos y creación de manuales."
        },
        skills: {
            categories: {
                net: "Redes & Seguridad",
                sys: "Sistemas & Workspace",
                cloud: "Cloud & DevOps",
                dev: "Desarrollo",
                db: "Bases de Datos",
                hw: "Hardware & Support",
                ia: "IA & Automatización",
                prod: "Productividad",
                langs: "Idiomas"
            },
            desc: {
                net: "Infraestructura, conectividad y seguridad de red.",
                sys: "Sistemas operativos y entornos de trabajo.",
                cloud: "Infraestructura escalable y automatización.",
                dev: "Lenguajes y herramientas de desarrollo.",
                db: "Gestión de datos masivos y estructurados.",
                hw: "Soporte de campo y entornos virtuales.",
                ia: "IA y optimización de flujos con n8n.",
                prod: "Gestión de proyectos y colaboración.",
                langs: "Comunicación en entornos globales."
            },
            items: {
                dns_desc: "Resolución y gestión de dominios",
                dhcp_desc: "IP dinámica y gestión de subredes",
                pfsense_desc: "Fundamentos de Firewall y Routing",
                cisco_desc: "Teléfonos IP y Redes Básicas",
                grandstream_desc: "Soporte de VoIP y Telefonía IP",
                wireshark_desc: "Análisis Básico de Paquetes",
                linux_desc: "Admin de servidores y diagnóstico",
                windows_desc: "Servidores, AD y soporte a usuarios",
                m365_desc: "Admin de Tenant y Apps Cloud",
                macos_desc: "Soporte y uso avanzado",
                mdm_desc: "Gestión de flotas iOS y Android",
                shell_desc: "Scripting Básico en Bash y PowerShell",
                azure_desc: "Fundamentos de Azure y Entra ID",
                aws_desc: "Conceptos Básicos de EC2 y S3",
                docker_desc: "Contenedores y Despliegues Básicos",
                k8s_desc: "Orquestación y escalado de clusters",
                terraform_desc: "Fundamentos de IaC",
                cloudflare_desc: "Seguridad WAF y rendimiento DNS",
                python_desc: "Backend, Scripting y FastAPI",
                js_desc: "Frontend (React) y Lógica",
                react_desc: "Interfaces web modernas y SPA",
                fastapi_desc: "APIs de alto rendimiento con Python",
                tailwind_desc: "Diseño web con CSS moderno",
                dotnet_desc: "C# y Aplicaciones .NET Básicas",
                htmlcss_desc: "Maquetación y estilos web",
                csharp_desc: "Aplicaciones de consola y sistema",
                git_desc: "Control de versiones y CI/CD",
                postgres_desc: "BD Relacional y Admin Básica",
                mysql_desc: "Gestión de BBDD Relacionales",
                sqlite_desc: "BBDD ligera para apps locales",
                mssql_desc: "Admin Básica de SQL Server",
                nosql_desc: "Gestión de documentos JSON",
                zebra_desc: "Impresoras Zebra e RFID especialista",
                honeywell_desc: "Soporte hardware industrial",
                igel_desc: "Thin Clients y Gestión Workspace",
                vmware_desc: "Entornos VMware y VirtualBox",
                vbox_desc: "Virtualización local avanzada",
                rpi_desc: "Sistemas embebidos y SBC",
                n8n_desc: "Automatización avanzada de flujos",
                copilot_desc: "Asistente IA para codificación",
                gemini_desc: "Uso de LLMs para productividad",
                llm_desc: "GPT, Gemini y Prompt Engineering",
                teams_desc: "Colaboración corporativa y Teams",
                office_desc: "Admin de aplicaciones Office 365",
                clickup_desc: "Gestión de tareas y proyectos",
                notion_desc: "Espacio de trabajo y documentación",
                jira_desc: "Gestión de incidencias y Agile",
                ansible_desc: "Gestión Básica de Configuración",
                vlan_desc: "Fundamentos de Segmentación de Red",
                ad_desc: "Gestión de dominios y usuarios AD",
                gpo_desc: "Políticas de grupo y seguridad",
                parallels_desc: "Virtualización en macOS",
                actions_desc: "Automatización de despliegues",
                oracle_desc: "Fundamentos de Oracle DB",
                access_desc: "BBDD relacionales con Office",
                json_desc: "Estructuras de datos y APIs",
                rfid_desc: "Sistemas de identificación por radio",
                peri_desc: "Soporte a periféricos y escáneres",
                ollama_desc: "Ejecución de LLMs en local",
                prompt_desc: "Optimización de consultas a IA",
                excel_desc: "Excel y Gestión de Datos",
                project_desc: "Planificación Básica de Proyectos",
                german_desc: "Conocimientos iniciales",
                agents_desc: "IA Agentes y LangChain",
                vector_desc: "Bases de datos Vectoriales",
                image_desc: "Generación de imágenes IA",
                redis_desc: "Caché y BD en Memoria Básica",
                diagnos_desc: "Diagnóstico avanzado de HW",
                vite_desc: "Herramientas de frontend rápidas",
                orm_desc: "Interacciones seguras con BBDD",
                sharp_desc: "Procesamiento de imágenes",
                pages_desc: "Hosting estático de alta disponibilidad",
                lighthouse_desc: "Optimización de SEO y rendimiento",
                python_fastapi: "Python / FastAPI",
                python_fastapi_desc: "Scripting en Python y Backend Básico",
                js_react: "JavaScript / React",
                js_react_desc: "Frontend y Lógica Básica",
                cicd: "CI/CD & Automatización",
                cicd_desc: "GitHub Actions y Hosting d'alta disp.",
                sqlite_orm: "SQLite & SQLModel",
                sqlite_orm_desc: "BBDD locales y Mapeo ORM",
                zebra_rfid: "Zebra & RFID",
                zebra_rfid_desc: "Impresoras industriales y Especialista RFID",
                honeywell_scan: "Escáneres Honeywell",
                honeywell_scan_desc: "Escaneo industrial y Soporte de Hardware",
                vminfra: "Infraestructura VM",
                vminfra_desc: "VMware ESXi y Operaciones VirtualBox",
                hw_diag: "Soporte HW & Diagnóstico",
                hw_diag_desc: "Periféricos avanzados y Resolución de averías",
                claude_code: "Claude / Claude Code",
                claude_code_desc: "Razonamiento avanzado y Herramientas CLI",
                openclaw: "OpenClaw",
                openclaw_desc: "Agentes de IA Autónomos",
                nanobanana: "Nano Banana Pro",
                nanobanana_desc: "Generación de Imágenes Profesional",
                openai_new: "OpenAI / GPT",
                openai_new_desc: "Uso de LLMs y Prompting",
                n8n_new: "Automatización n8n",
                n8n_new_desc: "Automatización Básica de Flujos"
            }
        },
        projects: {
            p1_desc: "Portafolio inspirado en iOS26 con HTML, CSS y JS. Modo oscuro/claro, selector de idioma y Dynamic Island como navegación.",
            p2_desc: "Aplicación de gestión hotelera con Python + PostgreSQL. Reservas, usuarios, seguridad, replicación y backups automáticos.",
            p3_desc: "Juego de acción con tres tipos de enemigos y mejoras de personaje. Hecho en Unity.",
            p4_desc: "Shooter 2D con power-ups, sistema de puntuación y oleadas. Hecho en Unity.",
            p5_desc: "Ecosistema integral on-premise (.NET 8 & React 19) para la gestión táctil de restaurantes. Control de comandas, impresión multi-cocina, delivery y facturación legal.",
            p5_details: {
                title: "Snack Tanger 303 – TPV & Management Ecosystem",
                subtitle: "Solución de gestión 360° para restauración moderna",
                description: "Plataforma profesional diseñada para optimizar el ciclo completo de un restaurante. Desde la toma de pedidos táctil hasta el cierre de caja contable, el sistema garantiza una operación estable y eficiente sin dependencia de la nube.",
                features: [
                    "Gestión Táctil: UX optimizada para pantallas industriales.",
                    "Multi-Delivery: Integración de Uber Eats, Glovo y Just Eat.",
                    "Facturación Legal: Reportes Informe Z y tickets legales.",
                    "Control de Cajas: Gestión total de arqueos y cierres locales."
                ],
                stack: [".NET", "React", "SQLite", "TailwindCSS", "Entity Framework", "ESC/POS", "GitHub"]
            },
            p2_details: {
                title: "Hotel Management System",
                subtitle: "Gestión integral de cadenas hoteleras",
                description: "Aplicación robusta para la administración de reservas, clientes, personal y auditoría de datos. Incluye sistemas de seguridad avanzada y backups automáticos.",
                features: ["Control de reservas y huéspedes", "Gestión de personal y servicios", "Base de datos PostgreSQL con replicación", "Exportación de informes JSON/PDF"],
                stack: ["Linux", "PostgreSQL", "Python", "SQL", "Bash", "Git", "GitHub"]
            },
            p3_details: {
                title: "ERAY Slasher – Roguelite Shooter",
                subtitle: "Videojuego de acción ambientado en el siglo XVIII",
                description: "Un shooter de acción donde controlas a ERAY, defendiendo su hogar con habilidades mágicas frente a hordas de enemigos dinámicos.",
                features: ["Sistema de oleadas y enemigos", "Mejoras de estadísticas y objetos", "Motor de física Unity 2D", "Diseño artístico original"],
                stack: ["Unity", "C#", ".NET", "Visual Studio", "Git", "GitHub"]
            },
            p7_desc: "Ecosistema integral TPV y Carta Digital para The Kebab Lab. Gestión de pedidos en tiempo real, KDS, administración avanzada y despliegue automático.",
            p7_details: {
                title: "The Kebab Lab – TPV & Management Ecosystem",
                subtitle: "Solución de gestión 360° para restauración moderna",
                description: "Plataforma profesional diseñada para optimizar el ciclo completo de un restaurante. Basado en el ecosistema Snack Tanger, adaptado a las necesidades específicas de The Kebab Lab.",
                features: [
                    "Gestión Táctil: UX optimizada para tablets.",
                    "Multi-Delivery: Integración de plataformas externas.",
                    "Facturación Legal: Reportes Informe Z y tickets legales.",
                    "Smart Printing: Sistema ESC/POS para cocina y barra."
                ],
                stack: [".NET", "React", "SQLite", "TailwindCSS", "Entity Framework", "ESC/POS", "GitHub"]
            },
            p8_desc: "Plataforma web corporativa y marketplace de licencias VTC en España. Incluye gestión de licencias (comprar/vender), blog del sector y panel de administración en /admin.",
            p8_details: {
                title: "GetVTC – Marketplace & Consultoría VTC",
                subtitle: "Plataforma web corporativa y gestión de licencias VTC",
                description: "Plataforma integral orientada al sector VTC en España. Combina una web pública con marketplace para comprar, vender y solicitar licencias con un panel de administración para la gestión de clientes y contenidos.",
                features: [
                    "Marketplace VTC: Gestión de ofertas de licencias en tiempo real.",
                    "Panel Admin: Control de leads, solicitudes y publicaciones.",
                    "Contenido & Blog: Sección de actualidad y ofertas de empleo.",
                    "Arquitectura Serverless: Despliegue en Cloudflare Pages con backend Supabase."
                ],
                stack: ["Next.js", "TypeScript", "PostgreSQL", "TailwindCSS", "Cloudflare", "GitHub"]
            },
            p9_desc: "Galería web pública de imágenes gastronómicas generadas con IA de alta calidad para cartas digitales, TPVs y marketing sin costes de almacenamiento.",
            p9_details: {
                title: "FoodPix – Food Image Hub",
                subtitle: "Galería de imágenes gastronómicas generadas con IA",
                description: "Banco de imágenes de alta resolución dedicado a la restauración. Permite a propietarios y desarrolladores obtener fotografías de comida para menús digitales y TPVs sin derechos de autor.",
                features: [
                    "Almacenamiento Cloudflare R2: 10GB de imágenes servidas en WebP.",
                    "Internacionalización: Soporte multiidioma (ES/EN/FR).",
                    "Cero Costes: Operatividad total sobre la capa gratuita de Cloudflare.",
                    "Panel Admin: Gestión de catálogo a través de Pages Functions."
                ],
                stack: ["React", "Vite", "TailwindCSS", "Cloudflare", "GitHub"]
            },
            p10_desc: "Sistema web de reservas online en tiempo real para barberías con notificaciones automáticas por Telegram Bot API, gestión sin registro y TPV integrado.",
            p10_details: {
                title: "R7Sultan – Reservas & TPV Barbería",
                subtitle: "Plataforma de reservas en tiempo real y gestión TPV",
                description: "Sistema de reservas de última generación para barberías. Garantiza disponibilidad sin solapamientos mediante constraints en PostgreSQL y notifica instantáneamente al barbero vía Telegram.",
                features: [
                    "Control de Disponibilidad: Algoritmo anti-double booking en base de datos.",
                    "Notificaciones Instantáneas: Alertas automáticas por Telegram Bot y Email.",
                    "Acceso Directo: Gestión de cita mediante token único sin necesidad de registro.",
                    "Panel Admin & TPV: Control de citas, horarios y registro de cobros (Efectivo/Tarjeta/Bizum)."
                ],
                stack: ["Next.js", "TypeScript", "PostgreSQL", "TailwindCSS", "Cloudflare", "GitHub"]
            },
            p11_desc: "Web pública y panel de administración para el restaurante Amigos2. Gestión interactiva de carta digital, promociones y galería con backend Supabase.",
            p11_details: {
                title: "Amigos2 – Web & Admin Restauración",
                subtitle: "Plataforma web corporativa y panel de gestión",
                description: "Solución desacoplada en dos aplicaciones React (Web pública y Panel Admin) que permite al propietario gestionar la carta, promociones y fotos del restaurante de forma autónoma.",
                features: [
                    "Carta Digital: Categorías, productos, precios y alérgenos.",
                    "Panel de Gestión: Administración intuitiva en admin.amigos2.com.",
                    "Supabase Backend: Base de datos PostgreSQL, autenticación y storage.",
                    "Despliegue CD: Integración continua en Cloudflare Pages."
                ],
                stack: ["React", "Vite", "PostgreSQL", "TailwindCSS", "Cloudflare", "GitHub"]
            }
        },
        contact: { linkedin: "LinkedIn", email: "Email", github: "GitHub", whatsapp: "WhatsApp" },
        system: {
            cc: "Centro de Control",
            battery: "Batería",
            charging: "Cargando",
            config_battery: "Configuración de la batería...",
            wifi: "Wi-Fi",
            on: "Activado",
            known_networks: "Redes conocidas",
            wifi_settings: "Ajustes de Wi-Fi...",
            calendar: "Calendario",
            brightness: "Brillo",
            fullscreen: "Pantalla completa",
            download_cv: "Descargar CV",
            print_cv: "Imprimir CV",
            about_title: "Acerca de este Portfolio",
            languages: "Idiomas",
            theme: "Tema",
            dark: "Oscuro",
            light: "Claro",
            shortcuts_title: "Atajos de Teclado",
            open_spotlight: "Abrir Spotlight",
            toggle_theme: "Toggle Tema",
            close_modals: "Cerrar modales",
            nav_spotlight: "Navegar en Spotlight",
            select_result: "Seleccionar resultado",
            search_placeholder: "Buscar en el portfolio...",
            dark_mode: "Modo Oscuro",
            light_mode: "Modo Claro",
            suggestions: "Sugerencias",
            no_results: "Sin resultados",
            curr_pdf: "Currículum en PDF",
            date_settings: "Configuración de fecha y hora...",
            native: "Nativo / Bilingüe",
            prof_eng: "Competencia profesional",
            basic: "Conocimiento básico",
            a1_level: "Nivel Inicial A1",
            login_hint: "Pulsa Enter para entrar",
            mission: "La Misión",
            capabilities: "Funcionalidades Clave",
            engineered: "Tecnologías Utilizadas"
        },
        menubar: {
            apple_about: "Acerca de este Portfolio",
            apple_pref: "Ajustes del Sistema...",
            file: "Archivo",
            edit: "Edición",
            view: "Visualización",
            go: "Ir",
            window: "Ventana",
            help: "Ayuda",
            copy_email: "Copiar Email",
            copy_link: "Copiar LinkedIn",
            copy_wa: "Copiar WhatsApp",
            shortcuts: "Atajos de Teclado",
            open_windows: "Ventanas Abiertas",
            send_email: "Enviar un Email"
        },
        ctx: {
            reload: "Recargar",
            copy: "Copiar",
            paste: "Pegar"
        }
    },
    en: {
        nav: { home: "Home", projects: "Projects", experience: "Experience", skills: "Skills", contact: "Contact" },
        hero: { title_prefix: "Hi, I'm", subtitle: "IT support and administration specialist with experience in corporate and public environments. I manage Linux and Windows systems, networks, Microsoft 365, hardware, and databases, ensuring stable and efficient operations. I am motivated by resolving technical issues and improving the user experience." },
        cta: { view: "View projects", cv: "Download CV" },
        sections: { exp: "Experience", sk: "Skills", proj: "Projects", contact: "Contact",
            exp_desc: "HIPRA · My Home Market · Ajuntament",
            sk_desc: "Network · Cloud · Dev · IA",
            proj_desc: "Snack Tanger · ERAY · Hotel",
            contact_desc: "LinkedIn · Email · GitHub"
        },
        exp: {
            e1_place: "May 2026 - Present", e1_role: "IT Workplace Technician",
            e1_t1: "IT Procurement (SAP): Managing hardware purchases, quotes, and PoC (Try & Buy) testing.",
            e1_t2: "Industrial IT Projects: Deployment coordination of IT infrastructure in production plants.",
            e1_t3: "Hardware & Leasing: Apple/Dell corporate fleet administration, staging, and leasing contracts.",
            e1_t4: "AV Solutions: Video conferencing management (Cisco Room Bar, Evoko) and migration to MS Teams.",
            e1_t5: "IT Onboarding & Security: Leading weekly technical onboarding and cybersecurity training.",
            e1_t6: "Daily Operations: L2 technical support and resolving corporate & industrial tickets.",

            e2_place: "Jun 2025 - May 2026", e2_role: "IT Workplace Intern",
            e2_t1: "L2 Support & M365: Resolving complex issues and administering Microsoft 365 accounts.",
            e2_t2: "Ticketing & Staging: Remedy/SmartIT incident management and laptop/IGEL staging.",
            e2_t3: "Mobile & Printing: iOS/Android setup, Cisco VoIP, and RFID/thermal printers (Zebra/Honeywell).",
            e2_t4: "Security & Warranties: Vendor coordination for repairs and applying system security patches.",

            e3_place: "Jul 2020 - Jun 2025", e3_role: "Sales Assistant",
            e3_t1: "Customer Service: Tailored advice, customer assistance, and satisfaction optimization.",
            e3_t2: "Stock & Cash Management: Inventory control, product restocking, and cash register operations.",

            e4_place: "Nov 2023 – Apr 2024", e4_role: "IT Helpdesk Intern",
            e4_t1: "Municipal Support: On-site and remote IT support for municipal staff (HW, SW, networking).",
            e4_t2: "Systems & Documentation: Linux diagnostic tools, user permissions, and user guide creation."
        },
        skills: {
            categories: {
                net: "Networks & Security",
                sys: "Systems & Workspace",
                cloud: "Cloud & DevOps",
                dev: "Development",
                db: "Databases",
                hw: "Hardware & Support",
                ia: "AI & Automation",
                prod: "Productivity",
                langs: "Languages"
            },
            desc: {
                net: "Infrastructure, connectivity and network security.",
                sys: "Operating systems and work environments.",
                cloud: "Scalable infrastructure and automation.",
                dev: "Development languages and tools.",
                db: "Big data and structured data management.",
                hw: "Field support and virtual environments.",
                ia: "AI and workflow optimization with n8n.",
                prod: "Project management and collaboration.",
                langs: "Communication in global environments."
            },
            items: {
                dns_desc: "Domain resolution and management",
                dhcp_desc: "Dynamic IP and subnet management",
                pfsense_desc: "Firewall & Routing Basics",
                cisco_desc: "IP Phones & Basic Networking",
                grandstream_desc: "VoIP and IP Telephony Support",
                wireshark_desc: "Basic Packet Analysis",
                linux_desc: "Server administration and diagnostics",
                windows_desc: "Servers, AD and user support",
                m365_desc: "Tenant Admin and Cloud Apps",
                macos_desc: "Advanced support and expert use",
                mdm_desc: "iOS and Android fleet management",
                shell_desc: "Basic Bash & PowerShell Scripting",
                azure_desc: "Azure & Entra ID Fundamentals",
                aws_desc: "EC2 & S3 Basics",
                docker_desc: "Containers & Basic Deployments",
                k8s_desc: "Orchestration and cluster scaling",
                terraform_desc: "IaC Fundamentals",
                cloudflare_desc: "WAF security and DNS performance",
                python_desc: "Backend, Scripting and FastAPI",
                js_desc: "Frontend (React) and Logic",
                react_desc: "Modern web interfaces and SPAs",
                fastapi_desc: "High-performance Python APIs",
                tailwind_desc: "Modern CSS web design",
                dotnet_desc: "Basic C# & .NET Apps",
                htmlcss_desc: "Web layout and styling",
                csharp_desc: "Console and system applications",
                git_desc: "Version control and CI/CD",
                postgres_desc: "Relational DB & Basic Admin",
                mysql_desc: "Relational DB management",
                sqlite_desc: "Lightweight DB for local apps",
                mssql_desc: "Basic SQL Server Admin",
                nosql_desc: "JSON document management",
                zebra_desc: "Zebra printers and RFID specialist",
                honeywell_desc: "Industrial hardware support",
                igel_desc: "Thin Clients and Workspace Management",
                vmware_desc: "VMware and VirtualBox environments",
                vbox_desc: "Advanced local virtualization",
                rpi_desc: "Embedded systems and SBC",
                n8n_desc: "Advanced workflow automation",
                copilot_desc: "AI-powered coding assistant",
                gemini_desc: "LLMs for productivity use",
                llm_desc: "GPT, Gemini and Prompt Engineering",
                teams_desc: "Corporate collaboration & Teams",
                office_desc: "Office 365 apps administration",
                clickup_desc: "Task and project management",
                notion_desc: "Workspace and documentation",
                jira_desc: "Issue tracking and Agile",
                ansible_desc: "Basic Configuration Management",
                vlan_desc: "Network Segmentation Fundamentals",
                ad_desc: "Domain & User Management (AD)",
                gpo_desc: "Group Policies & Security",
                parallels_desc: "macOS Virtualization",
                actions_desc: "Deployment Automation",
                oracle_desc: "Oracle DB Fundamentals",
                access_desc: "Relational DBs with Office",
                json_desc: "Data structures & APIs",
                rfid_desc: "Radio-Frequency ID Systems",
                peri_desc: "Peripherals & Scanner Support",
                ollama_desc: "Running local LLMs",
                prompt_desc: "AI Query Optimization",
                excel_desc: "Excel & Data Management",
                project_desc: "Basic Project Planning",
                german_desc: "Initial knowledge",
                agents_desc: "AI Agents & LangChain",
                vector_desc: "Vector Databases",
                image_desc: "AI Image Generation",
                redis_desc: "Cache & In-memory DB Basics",
                diagnos_desc: "Advanced HW Diagnosis",
                vite_desc: "Next-gen frontend tooling",
                orm_desc: "Type-safe DB interactions",
                sharp_desc: "High-performance image processing",
                pages_desc: "High-availability static hosting",
                lighthouse_desc: "SEO & performance audit",
                python_fastapi: "Python / FastAPI",
                python_fastapi_desc: "Python Scripting & Basic Backend",
                js_react: "JavaScript / React",
                js_react_desc: "Frontend & Basic Logic",
                cicd: "CI/CD & Automation",
                cicd_desc: "GitHub Actions & High-availability Hosting",
                sqlite_orm: "SQLite & SQLModel",
                sqlite_orm_desc: "Local DBs & ORM Mapping",
                zebra_rfid: "Zebra & RFID",
                zebra_rfid_desc: "Industrial Printers & RFID Specialist",
                honeywell_scan: "Honeywell Scanners",
                honeywell_scan_desc: "Industrial Scanning & HW Support",
                igel_new: "Thin Clients (IGEL)",
                igel_new_desc: "IGEL OS & Workspace Management",
                vminfra: "VM Infrastructure",
                vminfra_desc: "VMware ESXi & VirtualBox Ops",
                hw_diag: "HW Support & Diagnostics",
                hw_diag_desc: "Advanced Peripherals & HW Troubleshooting",
                n8n_new: "n8n Automation",
                n8n_new_desc: "Basic Workflow Automation",
                chatgpt_new: "ChatGPT",
                chatgpt_new_desc: "Expert LLM Prompting & Analysis",
                claude_new: "Claude / Claude Code",
                claude_new_desc: "Advanced Reasoning & CLI Tools",
                openclaw_new: "OpenClaw",
                openclaw_new_desc: "Autonomous AI Agents",
                nanobanana_new: "Nano Banana Pro",
                nanobanana_new_desc: "Professional Image Generation",
                openai_new: "OpenAI / GPT",
                openai_new_desc: "LLM Usage & Prompting"
            }
        },
        projects: {
            p1_desc: "iOS26-inspired portfolio with HTML, CSS & JS. Dark/light mode, language selector, and Dynamic Island navigation.",
            p2_desc: "Hotel management app built with Python + PostgreSQL. Reservations, guest management, replication, and automatic backups.",
            p3_desc: "Action slasher with 3 enemy types and character upgrades. Built with Unity.",
            p4_desc: "2D space shooter featuring power-ups, scoring system, and enemy waves. Built with Unity.",
            p5_desc: "On-premise ecosystem (.NET 8 & React 19) for tactile restaurant management. Order control, multi-kitchen printing, delivery, and legal invoicing.",
            p5_details: {
                title: "Snack Tanger 303 – POS & Management Ecosystem",
                subtitle: "360° Management Solution for Modern Restaurants",
                description: "Professional platform designed to optimize the complete cycle of a restaurant. From tactile order taking to daily accounting closing, the system ensures stable and efficient operation without cloud dependency.",
                features: [
                    "Touch Management: Optimized UX for industrial screens.",
                    "Multi-Delivery: Uber Eats, Glovo, and Just Eat integration.",
                    "Legal Invoicing: Z-Reports and legal billing compliance.",
                    "Cash Control: Full control of local audits and closings."
                ],
                stack: [".NET", "React", "SQLite", "TailwindCSS", "Entity Framework", "ESC/POS", "GitHub"]
            },
            p2_details: {
                title: "Hotel Management System",
                subtitle: "Integrated Management for Hotel Chains",
                description: "Robust application for managing reservations, guests, staff, and data auditing. Includes advanced security systems and automatic backups.",
                features: ["Reservations and guest control", "Staff and services management", "PostgreSQL database with replication", "JSON/PDF report exports"],
                stack: ["Linux", "PostgreSQL", "Python", "SQL", "Bash", "Git", "GitHub"]
            },
            p3_details: {
                title: "ERAY Slasher – Roguelite Shooter",
                subtitle: "18th-century Action Video Game",
                description: "An action shooter where you control ERAY, defending his home with magical abilities against waves of dynamic enemies.",
                features: ["Wave and enemy system", "Stats and item upgrades", "Unity 2D physics engine", "Original artistic design"],
                stack: ["Unity", "C#", ".NET", "Visual Studio", "Git", "GitHub"]
            },
            p7_desc: "Integrated POS System and Digital Menu for The Kebab Lab. Real-time order management, KDS, advanced administration, and automated deployment.",
            p7_details: {
                title: "The Kebab Lab – POS & Management Ecosystem",
                subtitle: "360° Management Solution for Modern Restaurants",
                description: "Professional platform designed to optimize the complete cycle of a restaurant. Based on the Snack Tanger ecosystem, adapted to the specific needs of The Kebab Lab.",
                features: [
                    "Touch Management: Optimized UX for tablets.",
                    "Multi-Delivery: External platform integration.",
                    "Legal Invoicing: Z-Reports and legal tickets.",
                    "Smart Printing: ESC/POS system for kitchen and bar."
                ],
                stack: [".NET", "React", "SQLite", "TailwindCSS", "Entity Framework", "ESC/POS", "GitHub"]
            },
            p8_desc: "Corporate web platform and VTC license marketplace in Spain. Includes license management (buy/sell), sector blog, and admin dashboard at /admin.",
            p8_details: {
                title: "GetVTC – VTC Marketplace & Consulting",
                subtitle: "Corporate Web Platform & VTC License Management",
                description: "Comprehensive platform tailored for the VTC sector in Spain. Combines a public web with a marketplace for buying, selling, and requesting licenses with a private admin dashboard.",
                features: [
                    "VTC Marketplace: Real-time license offers management.",
                    "Admin Dashboard: Control of leads, requests, and posts.",
                    "Blog & Content: Industry news section and job offers.",
                    "Serverless Architecture: Cloudflare Pages deployment with Supabase backend."
                ],
                stack: ["Next.js", "TypeScript", "PostgreSQL", "TailwindCSS", "Cloudflare", "GitHub"]
            },
            p9_desc: "Public web gallery of AI-generated high-quality food photography for digital menus, POS kiosks, and marketing with zero storage costs.",
            p9_details: {
                title: "FoodPix – Food Image Hub",
                subtitle: "AI-Generated Food Photography Gallery",
                description: "High-resolution image hub dedicated to food service. Enables restaurant owners and developers to get royalty-free food photos for digital menus and POS systems.",
                features: [
                    "Cloudflare R2 Storage: 10GB of WebP images served lightning fast.",
                    "Internationalization: Multi-language support (ES/EN/FR).",
                    "Zero Cost: Fully operational on Cloudflare's free tier.",
                    "Admin Panel: Catalog management via Pages Functions."
                ],
                stack: ["React", "Vite", "TailwindCSS", "Cloudflare", "GitHub"]
            },
            p10_desc: "Real-time online booking web system for barber shops with automatic notifications via Telegram Bot API, guest booking, and built-in POS.",
            p10_details: {
                title: "R7Sultan – Barber Booking & POS",
                subtitle: "Real-Time Booking Platform & POS System",
                description: "Next-gen booking system for barber shops. Guarantees zero double-booking via PostgreSQL constraints and instantly notifies barbers via Telegram.",
                features: [
                    "Availability Control: Database-level anti-double booking algorithm.",
                    "Instant Alerts: Automatic notifications via Telegram Bot & Email.",
                    "Guest Booking: Unique token appointment management without account registration.",
                    "Admin & POS Panel: Management of appointments, working hours, and cash/card checkout."
                ],
                stack: ["Next.js", "TypeScript", "PostgreSQL", "TailwindCSS", "Cloudflare", "GitHub"]
            },
            p11_desc: "Public web and admin panel for Amigos2 restaurant. Interactive digital menu management, promotions, and gallery powered by Supabase.",
            p11_details: {
                title: "Amigos2 – Restaurant Web & Admin",
                subtitle: "Corporate Web Platform & Management Panel",
                description: "Decoupled dual React solution (Public Web & Admin Panel) enabling the restaurant owner to manage menus, promotions, and photos autonomously.",
                features: [
                    "Digital Menu: Categories, items, pricing, and allergen indicators.",
                    "Admin Panel: Intuitive management dashboard at admin.amigos2.com.",
                    "Supabase Backend: PostgreSQL database, auth, and media storage.",
                    "CD Deployment: Continuous integration on Cloudflare Pages."
                ],
                stack: ["React", "Vite", "PostgreSQL", "TailwindCSS", "Cloudflare", "GitHub"]
            }
        },
        contact: { linkedin: "LinkedIn", email: "Email", github: "GitHub", whatsapp: "WhatsApp" },
        system: {
            cc: "Control Center",
            battery: "Battery",
            charging: "Charging",
            config_battery: "Battery Settings...",
            wifi: "Wi-Fi",
            on: "On",
            known_networks: "Known Networks",
            wifi_settings: "Wi-Fi Settings...",
            calendar: "Calendar",
            brightness: "Brightness",
            fullscreen: "Fullscreen",
            download_cv: "Download CV",
            print_cv: "Print CV",
            about_title: "About This Portfolio",
            languages: "Languages",
            theme: "Theme",
            dark: "Dark",
            light: "Light",
            shortcuts_title: "Keyboard Shortcuts",
            open_spotlight: "Open Spotlight",
            toggle_theme: "Toggle Theme",
            close_modals: "Close modals",
            nav_spotlight: "Navigate in Spotlight",
            select_result: "Select result",
            search_placeholder: "Search in portfolio...",
            dark_mode: "Dark Mode",
            light_mode: "Light Mode",
            suggestions: "Suggestions",
            no_results: "No results",
            mission: "The Mission",
            capabilities: "Key Capabilities",
            engineered: "Engineered With",
            curr_pdf: "Curriculum in PDF",
            main_section: "Main Section",
            tpv_desc: "Integral POS System",
            date_settings: "Date & Time Settings...",
            native: "Native / Bilingual",
            prof_eng: "Professional Proficiency",
            basic: "Basic Knowledge",
            a1_level: "A1 Beginner",
            login_hint: "Press Enter to log in"
        },
        menubar: {
            apple_about: "About This Portfolio",
            apple_pref: "System Settings...",
            file: "File",
            edit: "Edit",
            view: "View",
            go: "Go",
            window: "Window",
            help: "Help",
            copy_email: "Copy Email",
            copy_link: "Copy LinkedIn",
            copy_wa: "Copy WhatsApp",
            shortcuts: "Keyboard Shortcuts",
            open_windows: "Open Windows",
            send_email: "Send an Email"
        },
        ctx: {
            reload: "Reload",
            copy: "Copy",
            paste: "Paste"
        }
    },
    ca: {
        nav: { home: "Inici", projects: "Projectes", experience: "Experiència", skills: "Habilitats", contact: "Contacte" },
        hero: { title_prefix: "Hola, sóc", subtitle: "Especialista en suport i administració IT, amb experiència en entorns corporatius i públics. Gestiono sistemes Linux i Windows, xarxes, Microsoft 365, maquinari i bases de dades, assegurant operacions estables i eficients. Em motiva resoldre incidències tècniques i millorar l'experiència de l'usuari." },
        cta: { view: "Veure projectes", cv: "Descarregar CV" },
        sections: { exp: "Experiència", sk: "Habilitats", proj: "Projectes", contact: "Contacte",
            exp_desc: "HIPRA · My Home Market · Ajuntament",
            sk_desc: "Xarxes · Cloud · Dev · IA",
            proj_desc: "Snack Tanger · ERAY · Hotel",
            contact_desc: "LinkedIn · Email · GitHub"
        },
        exp: {
            e1_place: "Maig 2026 - Present", e1_role: "IT Workplace Technician",
            e1_t1: "IT Procurement (SAP): Gestió de compres de maquinari, pressupostos i proves PoC (Try and Buy).",
            e1_t2: "Projectes Industrials: Coordinació del desplegament d'infraestructura IT en plantes de producció.",
            e1_t3: "Maquinari i Rènting: Administració de dispositius Apple/Dell, aprovisionament i contractes de rènting.",
            e1_t4: "Sales AV: Gestió de sales de videoconferència (Cisco Room Bar, Evoko) i migració a MS Teams.",
            e1_t5: "IT Onboarding i Seguretat: Sessions setmanals d'acollida tècnica i bones pràctiques en ciberseguretat.",
            e1_t6: "Operacions Diàries: Suport tècnic L2 i resolució d'incidències corporatives i industrials.",

            e2_place: "Juny 2025 - Maig 2026", e2_role: "IT Workplace Intern",
            e2_t1: "Suport L2 i M365: Resolució d'incidències complexes i gestió d'usuaris Microsoft 365.",
            e2_t2: "Ticketing i Desplegaments: Incidències a Remedy/SmartIT i preparació d'equips (portàtils, IGEL).",
            e2_t3: "Mòbils i Impressió: Configuració d'iOS/Android, VoIP Cisco i impressores RFID/tèrmiques (Zebra/Honeywell).",
            e2_t4: "Seguretat i Garanties: Coordinació amb proveïdors de maquinari i desplegament de parches de seguretat.",

            e3_place: "Juliol 2020 - Juny 2025", e3_role: "Sales Assistant",
            e3_t1: "Atenció al Client: Assessorament personalitzat i identificació de necessitats.",
            e3_t2: "Gestió d'Estoc i Caixa: Control d'inventari, reposició de productes i operacions de caixa.",

            e4_place: "Novembre 2023 – Abril 2024", e4_role: "IT Helpdesk Intern",
            e4_t1: "Suport Municipal: Suport presencial i remot a usuaris municipals en maquinari, programari i xarxa.",
            e4_t2: "Sistemes i Guies: Diagnòstic amb eines Linux, gestió de permisos i creació de manuals d'usuari."
        },
        skills: {
            categories: {
                net: "Xarxes & Seguretat",
                sys: "Sistemes & Workspace",
                cloud: "Cloud & DevOps",
                dev: "Desenvolupament",
                db: "Bases de Dades",
                hw: "Maquinari & Support",
                ia: "IA & Automatització",
                prod: "Productivitat",
                langs: "Idiomes"
            },
            desc: {
                net: "Infraestructura, connectivitat i seguretat de xarxa.",
                sys: "Sistemes operatius i entorns de treball.",
                cloud: "Infraestructura escalable i automatització.",
                dev: "Llenguatges i eines de desenvolupament.",
                db: "Gestió de dades massives i estructurades.",
                hw: "Suport de camp i entorns virtuals.",
                ia: "IA i optimització de fluxos amb n8n.",
                prod: "Gestió de projectes i col·laboració.",
                langs: "Comunicació en entorns globals."
            },
            items: {
                dns_desc: "Resolució i gestió de dominis",
                dhcp_desc: "IP dinàmica i gestió de subxarxes",
                pfsense_desc: "Fonaments de Firewall i Routing",
                cisco_desc: "Telèfons IP i Xarxes Bàsiques",
                grandstream_desc: "Suport de VoIP i Telefonia IP",
                wireshark_desc: "Anàlisi Bàsic de Paquets",
                linux_desc: "Admin de servidors i diagnòstic",
                windows_desc: "Servidors, AD i suport a usuaris",
                m365_desc: "Admin de Tenant i Apps Cloud",
                macos_desc: "Suport avançat i ús expert",
                mdm_desc: "Gestió de flotes iOS i Android",
                shell_desc: "Scripting Bàsic en Bash i PowerShell",
                azure_desc: "Fonaments d'Azure i Entra ID",
                aws_desc: "Conceptes Bàsics d'EC2 i S3",
                docker_desc: "Contenidors i Desplegaments Bàsics",
                k8s_desc: "Orquestració i escalat de clusters",
                terraform_desc: "Fonaments d'IaC",
                cloudflare_desc: "Seguretat WAF i rendiment DNS",
                python_desc: "Backend, Scripting i FastAPI",
                js_desc: "Frontend (React) i Lògica",
                react_desc: "Interfícies web modernes i SPA",
                fastapi_desc: "APIs d'alt rendiment amb Python",
                tailwind_desc: "Disseny web amb CSS modern",
                dotnet_desc: "C# i Aplicacions .NET Bàsiques",
                htmlcss_desc: "Maquetació i estils web",
                csharp_desc: "Aplicacions de consola i sistema",
                git_desc: "Control de versions i CI/CD",
                postgres_desc: "BD Relacional i Admin Bàsica",
                mysql_desc: "Gestió de BBDD Relacionals",
                sqlite_desc: "BBDD lleugera per a apps locals",
                mssql_desc: "Admin Bàsica de SQL Server",
                nosql_desc: "Gestió de documents JSON",
                zebra_desc: "Impressores Zebra i RFID especialista",
                honeywell_desc: "Suport maquinari industrial",
                igel_desc: "Thin Clients i Gestió Workspace",
                vmware_desc: "Entorns VMware i VirtualBox",
                vbox_desc: "Virtualització local avançada",
                rpi_desc: "Sistemes encastats i SBC",
                n8n_desc: "Automatització avançada de fluxos",
                copilot_desc: "Assistent IA per a codificació",
                gemini_desc: "Ús de LLMs per a productivitat",
                llm_desc: "GPT, Gemini i Prompt Engineering",
                teams_desc: "Col·laboració corporativa i Teams",
                office_desc: "Admin d'aplicacions Office 365",
                clickup_desc: "Gestió de tasques i projectes",
                notion_desc: "Espai de treball i documentació",
                jira_desc: "Gestió d'incidències i Agile",
                ansible_desc: "Gestió Bàsica de Configuració",
                vlan_desc: "Fonaments de Segmentació de Xarxa",
                ad_desc: "Gestió de dominis i usuaris AD",
                gpo_desc: "Polítiques de grup i seguretat",
                parallels_desc: "Virtualització a macOS",
                actions_desc: "Automatització de desplegaments",
                oracle_desc: "Fonaments d'Oracle DB",
                access_desc: "BBDD relacionals amb Office",
                json_desc: "Estructures de dades i APIs",
                rfid_desc: "Sistemes d'identificació per ràdio",
                peri_desc: "Suport a perifèrics i escàners",
                ollama_desc: "Execució de LLMs en local",
                prompt_desc: "Optimització de consultes a IA",
                excel_desc: "Excel i Gestió de Dades",
                project_desc: "Planificació Bàsica de Projectes",
                german_desc: "Coneixements inicials",
                agents_desc: "IA Agents i LangChain",
                vector_desc: "Bases de dades Vectorials",
                image_desc: "Generació d'imatges IA",
                redis_desc: "Conceptes Bàsics de Memòria Cau i BD en Memòria",
                diagnos_desc: "Diagnòstic avançat de HW",
                vite_desc: "Eines de frontend d'última generació",
                orm_desc: "Interaccions segures amb BBDD",
                sharp_desc: "Processament d'imatges",
                pages_desc: "Hosting estàtic d'alta disponibilitat",
                lighthouse_desc: "Optimització de SEO i rendiment",
                python_fastapi: "Python / FastAPI",
                python_fastapi_desc: "Scripting en Python i Backend Bàsic",
                js_react: "JavaScript / React",
                js_react_desc: "Frontend i Lògica Bàsica",
                cicd: "CI/CD & Automatització",
                cicd_desc: "GitHub Actions i Hosting d'alta disp.",
                sqlite_orm: "SQLite & SQLModel",
                sqlite_orm_desc: "BBDD locals i Mapeig ORM",
                zebra_rfid: "Zebra & RFID",
                zebra_rfid_desc: "Impressores industrials i Especialista RFID",
                honeywell_scan: "Escàners Honeywell",
                honeywell_scan_desc: "Escaneig industrial i Suport de Hardware",
                vminfra: "Infraestructura VM",
                vminfra_desc: "VMware ESXi i Operacions VirtualBox",
                hw_diag: "Suport HW & Diagnòstic",
                hw_diag_desc: "Perifèrics avançats i Resolució d'averies",
                claude_code: "Claude / Claude Code",
                claude_code_desc: "Raonament avançat i Eines CLI",
                openclaw: "OpenClaw",
                openclaw_desc: "Agents de IA Autònoms",
                nanobanana: "Nano Banana Pro",
                nanobanana_desc: "Generació d'Imatges Professional",
                openai_new: "OpenAI / GPT",
                openai_new_desc: "Ús de LLMs i Prompting",
                n8n_new: "Automatització n8n",
                n8n_new_desc: "Automatització Bàsica de Fluxos"
            }
        },
        projects: {
            p1_desc: "Portafoli inspirat en iOS26 amb HTML, CSS i JS. Mode fosc/claro, selector d'idioma i Dynamic Island com a navegació.",
            p2_desc: "Aplicació de gestió hotelera amb Python + PostgreSQL. Reserves, usuaris, seguretat, replicació i còpies de seguretat automàtiques.",
            p3_desc: "Joc d'acció amb tres tipus d'enemics i millores de personatge. Fet en Unity.",
            p4_desc: "Shooter 2D amb power-ups, sistema de puntuació i onades. Fet en Unity.",
            p5_desc: "Ecosistema integral on-premise (.NET 8 & React 19) per a la gestió tàctil de restaurants. Control de comandes, impressió multi-cuina, delivery i facturació legal.",
            p5_details: {
                title: "Snack Tanger 303 – TPV & Management Ecosystem",
                subtitle: "Solució de gestió 360° per a restauració moderna",
                description: "Plataforma professional dissenyada per optimitzar el cicle complet d'un restaurant. Des de la presa de comandes tàctil fins al tancament de caixa comptable, el sistema garanteix una operació estable i eficient sense dependència del núvol.",
                features: [
                    "Gestió Tàctil: UX optimitzada per a tablets i pantalles industrials.",
                    "Multi-Delivery: Integració unificada d'Uber Eats, Glovo, Just Eat i repartiment propi.",
                    "Facturació Legal: Emissió de factures nominals, simplificades i informes Informe Z.",
                    "Impressió Intel·ligent: Sistema multi-impresora (Cuina/Bar) amb protocol ESC/POS.",
                    "Control de Caixa: Pagaments parcials, divisió de compte i gestió de descomptes.",
                    "Desplegament All-in-One: Executable únic que serveix API, BBDD i Web de forma local."
                ],
                stack: ["C#", ".NET 8", "React 19", "Vite", "TailwindCSS", "SQLite", "Entity Framework", "ESC/POS"]
            },
            p7_desc: "Ecosistema integral TPV i Carta Digital per a The Kebab Lab. Gestió de comandes en temps real, KDS, administració avançada i desplegament automàtic.",
            p7_details: {
                title: "The Kebab Lab – TPV & Management Ecosystem",
                subtitle: "Solució de gestió 360° per a restauració moderna",
                description: "Plataforma professional dissenyada per optimitzar el cicle complet d'un restaurant. Basat en l'ecosistema Snack Tanger, adaptat a les necessitats específiques de The Kebab Lab.",
                features: [
                    "Gestió Tàctil: UX optimitzada per a tablets.",
                    "Multi-Delivery: Integració de plataformes externes.",
                    "Facturació Legal: Informes Informe Z i tiquets legals.",
                    "Smart Printing: Sistema ESC/POS per a cuina i barra."
                ],
                stack: [".NET", "React", "SQLite", "TailwindCSS", "Entity Framework", "ESC/POS", "GitHub"]
            },
            p8_desc: "Plataforma web corporativa i marketplace de llicències VTC a Espanya. Inclou gestió de llicències (comprar/vendre), blog del sector i tauler d'administració a /admin.",
            p8_details: {
                title: "GetVTC – Marketplace & Consultoria VTC",
                subtitle: "Plataforma web corporativa i gestió de llicències VTC",
                description: "Plataforma integral orientada al sector VTC a Espanya. Combina una web pública amb marketplace per comprar, vendre i sol·licitar llicències amb un tauler d'administració per a la gestió de clients i continguts.",
                features: [
                    "Marketplace VTC: Gestió d'ofertes de llicències en temps real.",
                    "Tauler Admin: Control de leads, sol·licituds i publicacions.",
                    "Contingut & Blog: Secció d'actualitat i ofertes de feina.",
                    "Arquitectura Serverless: Desplegament a Cloudflare Pages amb backend Supabase."
                ],
                stack: ["Next.js", "TypeScript", "PostgreSQL", "TailwindCSS", "Cloudflare", "GitHub"]
            },
            p9_desc: "Galeria web pública d'imatges gastronòmiques generades amb IA d'alta qualitat per a cartes digitals, TPVs i màrqueting sense costos d'emmagatzematge.",
            p9_details: {
                title: "FoodPix – Food Image Hub",
                subtitle: "Galeria d'imatges gastronòmiques generades amb IA",
                description: "Banc d'imatges d'alta resolució dedicat a la restauració. Permet a propietaris i desenvolupadors obtenir fotografies de menjar per a menús digitals i TPVs sense drets d'autor.",
                features: [
                    "Emmagatzematge Cloudflare R2: 10GB d'imatges servides en WebP.",
                    "Internacionalització: Suport multiidioma (ES/EN/FR).",
                    "Zero Costos: Operativitat total sobre la capa gratuïta de Cloudflare.",
                    "Tauler Admin: Gestió de catàleg mitjançant Pages Functions."
                ],
                stack: ["React", "Vite", "TailwindCSS", "Cloudflare", "GitHub"]
            },
            p10_desc: "Sistema web de reserves online en temps real per a mebrosseries/barberies amb notificacions automàtiques per Telegram Bot API, gestió sense registre i TPV integrat.",
            p10_details: {
                title: "R7Sultan – Reserves & TPV Barberia",
                subtitle: "Plataforma de reserves en temps real i gestió TPV",
                description: "Sistema de reserves d'última generació per a barberies. Garanteix disponibilitat sense encavalcaments mitjançant constraints a PostgreSQL i notifica instantàniament al barber via Telegram.",
                features: [
                    "Control de Disponibilitat: Algoritme anti-double booking en base de dades.",
                    "Alertes Instantànies: Notificacions automàtiques per Telegram Bot i Email.",
                    "Accés Directe: Gestió de cita mitjançant token únic sense necessitat de registre.",
                    "Tauler Admin & TPV: Control de cites, horaris i registre de cobraments (Efectiu/Targeta/Bizum)."
                ],
                stack: ["Next.js", "TypeScript", "PostgreSQL", "TailwindCSS", "Cloudflare", "GitHub"]
            },
            p11_desc: "Web pública i tauler d'administració per al restaurant Amigos2. Gestió interactiva de carta digital, promocions i galeria amb backend Supabase.",
            p11_details: {
                title: "Amigos2 – Web & Admin Restauració",
                subtitle: "Plataforma web corporativa i tauler de gestió",
                description: "Solució desacoblada en dues aplicacions React (Web pública i Tauler Admin) que permet al propietari gestionar la carta, promocions i fotos del restaurant de forma autònoma.",
                features: [
                    "Carta Digital: Categories, productes, preus i al·lèrgens.",
                    "Tauler de Gestió: Administració intuïtiva a admin.amigos2.com.",
                    "Supabase Backend: Base de dades PostgreSQL, autenticació i emmagatzematge.",
                    "Desplegament CD: Integració contínua a Cloudflare Pages."
                ],
                stack: ["React", "Vite", "PostgreSQL", "TailwindCSS", "Cloudflare", "GitHub"]
            }
        },
        contact: { linkedin: "LinkedIn", email: "Email", github: "GitHub", whatsapp: "WhatsApp" },
        system: {
            cc: "Centre de Control",
            battery: "Bateria",
            charging: "Carregant",
            config_battery: "Configuració de la bateria...",
            wifi: "Wi-Fi",
            on: "Activat",
            known_networks: "Xarxes conegudes",
            wifi_settings: "Ajustos de Wi-Fi...",
            calendar: "Calendari",
            brightness: "Brillantor",
            fullscreen: "Pantalla completa",
            download_cv: "Descarregar CV",
            print_cv: "Imprimir CV",
            about_title: "Quant a aquest Portafoli",
            languages: "Idiomes",
            theme: "Tema",
            dark: "Fosc",
            light: "Clar",
            shortcuts_title: "Dreceres de Teclat",
            open_spotlight: "Obrir Spotlight",
            toggle_theme: "Toggle Tema",
            close_modals: "Tancar modals",
            nav_spotlight: "Navegar a Spotlight",
            select_result: "Seleccionar resultat",
            search_placeholder: "Cercar al portafoli...",
            dark_mode: "Mode Fosc",
            light_mode: "Mode Clar",
            suggestions: "Suggeriments",
            no_results: "Sense resultats",
            curr_pdf: "Currículum en PDF",
            date_settings: "Configuració de data i hora...",
            native: "Natiu / Bilingüe",
            prof_eng: "Competència professional",
            basic: "Coneixement bàsic",
            a1_level: "Nivell Inicial A1",
            login_hint: "Prem Enter per entrar"
        },
        menubar: {
            apple_about: "Quant a aquest Portafoli",
            apple_pref: "Ajustos del Sistema...",
            file: "Arxiu",
            edit: "Edició",
            view: "Visualització",
            go: "Ves-hi",
            window: "Finestra",
            help: "Ajuda",
            copy_email: "Copiar Email",
            copy_link: "Copiar LinkedIn",
            copy_wa: "Copiar WhatsApp",
            shortcuts: "Atajos de Teclat",
            open_windows: "Finestres Obertes",
            send_email: "Enviar un Email"
        },
        ctx: {
            reload: "Recarregar",
            copy: "Copiar",
            paste: "Enganxar"
        }
    },
    fr: {
        nav: { home: "Accueil", projects: "Projets", experience: "Expérience", skills: "Compétences", contact: "Contact" },
        hero: { title_prefix: "Salut, je suis", subtitle: "Spécialiste en assistance et administration informatique, avec une expérience dans les environnements d'entreprise et publics. Je gère les systèmes Linux et Windows, les réseaux, Microsoft 365, le matériel et les bases de données, en garantissant des opérations stables et efficaces. Je suis motivé par la résolution des incidents techniques et l'amélioration de l'expérience utilisateur." },
        cta: { view: "Voir les projets", cv: "Télécharger le CV" },
        sections: { exp: "Expérience", sk: "Compétences", proj: "Projets", contact: "Contact",
            exp_desc: "HIPRA · My Home Market · Ajuntament",
            sk_desc: "Réseaux · Cloud · Dev · IA",
            proj_desc: "Snack Tanger · ERAY · Hotel",
            contact_desc: "LinkedIn · Email · GitHub"
        },
        exp: {
            e1_place: "Mai 2026 - Présent", e1_role: "IT Workplace Technician",
            e1_t1: "IT Procurement (SAP): Gestion des achats matériel, devis et tests PoC (Try and Buy).",
            e1_t2: "Projets Industriels: Coordination du déploiement d'infrastructures IT sur les sites de production.",
            e1_t3: "Matériel & Leasing: Administration du parc Apple/Dell, approvisionnement et contrats de leasing.",
            e1_t4: "Salles AV: Gestion des équipements de visioconférence (Cisco Room Bar, Evoko) et migration vers MS Teams.",
            e1_t5: "IT Onboarding & Sécurité: Animation des sessions d'intégration technique et formation en cybersécurité.",
            e1_t6: "Opérations Quotidiennes: Support technique L2 et résolution des tickets d'entreprise et industriels.",

            e2_place: "Juin 2025 - Mai 2026", e2_role: "IT Workplace Intern",
            e2_t1: "Support L2 & M365: Résolution d'incidents complexes et administration des comptes Microsoft 365.",
            e2_t2: "Ticketing & Masterisation: Gestion des tickets (Remedy/SmartIT) et déploiement de PC et clients IGEL.",
            e2_t3: "Mobiles & Impression: Configuration iOS/Android, VoIP Cisco et imprimantes thermiques/RFID (Zebra/Honeywell).",
            e2_t4: "Sécurité & Garanties: Coordination fournisseurs pour réparations et déploiement des correctifs de sécurité.",

            e3_place: "Juillet 2020 - Juin 2025", e3_role: "Sales Assistant",
            e3_t1: "Service Client: Conseil personnalisé et accompagnement pour maximiser la satisfaction client.",
            e3_t2: "Stocks & Caisse: Gestion de l'inventaire, réapprovisionnement et encaissement.",

            e4_place: "Novembre 2023 – Avril 2024", e4_role: "IT Helpdesk Intern",
            e4_t1: "Support Municipal: Support technique sur site et à distance pour le personnel municipal.",
            e4_t2: "Systèmes & Guides: Diagnostic Linux, gestion des autorisations et rédaction de guides utilisateurs."
        },
        skills: {
            categories: {
                net: "Réseaux & Sécurité",
                sys: "Systèmes & Workspace",
                cloud: "Cloud & DevOps",
                dev: "Développement",
                db: "Bases de Données",
                hw: "Matériel & Support",
                ia: "IA & Automatisation",
                prod: "Productivité",
                langs: "Langues"
            },
            desc: {
                net: "Infrastructure, connectivité et sécurité réseau.",
                sys: "Systèmes d'exploitation et environnements de travail.",
                cloud: "Infrastructure évolutive et automatisation.",
                dev: "Langages et outils de développement.",
                db: "Gestion de données massives et structurées.",
                hw: "Support terrain et environnements virtuels.",
                ia: "IA et optimisation de flux avec n8n.",
                prod: "Gestion de projets et collaboration.",
                langs: "Communication dans des environnements mondiaux."
            },
            items: {
                dns_desc: "Résolution et gestion de domaines",
                dhcp_desc: "IP dynamique et gestion de sous-réseaux",
                pfsense_desc: "Fondamentaux Pare-feu et Routage",
                cisco_desc: "Téléphones IP et Réseaux de base",
                grandstream_desc: "Support VoIP et téléphonie IP",
                wireshark_desc: "Analyse basique de paquets",
                linux_desc: "Admin serveurs et diagnostic",
                windows_desc: "Serveurs, AD et support utilisateur",
                m365_desc: "Admin Tenant et Apps Cloud",
                macos_desc: "Support avancé et usage expert",
                mdm_desc: "Gestion de flottes iOS et Android",
                shell_desc: "Scripting de base en Bash et PowerShell",
                azure_desc: "Fondamentaux Azure et Entra ID",
                aws_desc: "Bases EC2 et S3",
                docker_desc: "Conteneurs et déploiements basiques",
                k8s_desc: "Orchestration et mise à l'échelle de clusters",
                terraform_desc: "Fondamentaux IaC",
                cloudflare_desc: "Sécurité WAF et performance DNS",
                python_desc: "Backend, Scripting et FastAPI",
                js_desc: "Frontend (React) et logique",
                react_desc: "Interfaces web modernes et SPAs",
                fastapi_desc: "APIs Python haute performance",
                tailwind_desc: "Conception web CSS moderne",
                dotnet_desc: "Applications C# et .NET de base",
                htmlcss_desc: "Mise en page et styles web",
                csharp_desc: "Applications console et système",
                git_desc: "Contrôle de version et CI/CD",
                postgres_desc: "BD relationnelle et admin de base",
                mysql_desc: "Gestion de BBDD relationnelles",
                sqlite_desc: "BBDD légère pour apps locales",
                mssql_desc: "Admin SQL Server de base",
                nosql_desc: "Gestion de documents JSON",
                zebra_desc: "Imprimantes Zebra et RFID spécialiste",
                honeywell_desc: "Support matériel industriel",
                igel_desc: "Clients légers et gestion de l'espace de travail",
                vmware_desc: "Environnements VMware et VirtualBox",
                vbox_desc: "Virtualisation locale avancée",
                rpi_desc: "Systèmes embarqués et SBC",
                n8n_desc: "Automatisation avancée des flux",
                copilot_desc: "Assistant de codage IA",
                gemini_desc: "Utilisation de LLM pour la productivité",
                llm_desc: "GPT, Gemini et Prompt Engineering",
                teams_desc: "Collaboration d'entreprise et Teams",
                office_desc: "Admin d'applications Office 365",
                clickup_desc: "Gestion de tâches et projets",
                notion_desc: "Espace de travail et documentation",
                jira_desc: "Gestion d'incidents et Agile",
                ansible_desc: "Gestion de configuration de base",
                vlan_desc: "Fondamentaux de segmentation réseau",
                ad_desc: "Gestion de domaines et d'utilisateurs AD",
                gpo_desc: "Stratégies de groupe et sécurité",
                parallels_desc: "Virtualisation sur macOS",
                actions_desc: "Automatisation des déploiements",
                oracle_desc: "Fondamentaux Oracle DB",
                access_desc: "BBDD relationnelles avec Office",
                json_desc: "Structures de données et APIs",
                rfid_desc: "Systèmes d'identification radio",
                peri_desc: "Support périphériques et scanners",
                ollama_desc: "Exécution de LLM en local",
                prompt_desc: "Optimisation des requêtes IA",
                excel_desc: "Excel et gestion de données",
                project_desc: "Planification de base de projets",
                german_desc: "Connaissances initiales",
                agents_desc: "Agents IA et LangChain",
                vector_desc: "Bases de données vectorielles",
                image_desc: "Génération d'images IA",
                redis_desc: "Bases de cache et BD en mémoire",
                diagnos_desc: "Diagnostic matériel avancé",
                vite_desc: "Outils frontend de nouvelle génération",
                orm_desc: "Interactions sécurisées avec les BBDD",
                sharp_desc: "Traitement d'images haute performance",
                pages_desc: "Hébergement statique haute disponibilité",
                lighthouse_desc: "Audit SEO et performance",
                python_fastapi: "Python / FastAPI",
                python_fastapi_desc: "Scripting Python et Backend de base",
                js_react: "JavaScript / React",
                js_react_desc: "Frontend et logique de base",
                cicd: "CI/CD & Automatisation",
                cicd_desc: "GitHub Actions et Hébergement haute disp.",
                sqlite_orm: "SQLite & SQLModel",
                sqlite_orm_desc: "BBDD locales et Cartographie ORM",
                zebra_rfid: "Zebra & RFID",
                zebra_rfid_desc: "Imprimantes industrielles et Spécialiste RFID",
                honeywell_scan: "Scanners Honeywell",
                honeywell_scan_desc: "Numérisation industrielle et Support Matériel",
                igel_new: "Clients Légers (IGEL)",
                igel_new_desc: "IGEL OS et Gestion de l'espace de travail",
                vminfra: "Infrastructure VM",
                vminfra_desc: "VMware ESXi et Opérations VirtualBox",
                hw_diag: "Support HW & Diagnostic",
                hw_diag_desc: "Périphériques avancés et Dépannage Matériel",
                n8n_new: "Automatisation n8n",
                n8n_new_desc: "Automatisation de flux de base",
                chatgpt_new: "ChatGPT",
                chatgpt_new_desc: "Expertise en Prompting et Analyse LLM",
                claude_new: "Claude / Claude Code",
                claude_new_desc: "Raisonnement avancé et Outils CLI",
                openclaw_new: "OpenClaw",
                openclaw_new_desc: "Agents d’IA Autonomes",
                nanobanana_new: "Nano Banana Pro",
                nanobanana_new_desc: "Génération d'Images Professionnelle",
                openai_new: "OpenAI / GPT",
                openai_new_desc: "Utilisation de LLM et Prompting"
            }
        },
        projects: {
            p1_desc: "Portfolio inspiré d'iOS26 avec HTML, CSS & JS. Mode sombre/clair, sélecteur de langue et Dynamic Island.",
            p2_desc: "Application de gestion hôtelière en Python + PostgreSQL. Réservations, utilisateurs, réplication et sauvegardes.",
            p3_desc: "Jeu d'action avec 3 types d'ennemis et améliorations de personnage. Conçu avec Unity.",
            p4_desc: "Shooter 2D avec power-ups, système de score et vagues d'ennemis. Conçu avec Unity.",
            p5_desc: "Écosystème on-premise (.NET 8 & React 19) pour la gestion tactile des restaurants. Contrôle des commandes, impression multi-cuisine, livraison et facturation légale.",
            p5_details: {
                title: "Snack Tanger 303 – TPV & Management Ecosystem",
                subtitle: "Solution de gestion 360° pour la restauration moderne",
                description: "Plateforme professionnelle conçue pour optimiser le cycle complet d'un restaurant. De la prise de commande tactile à la clôture comptable, le système garantit un fonctionnement stable sans dépendance au cloud.",
                features: [
                    "Gestion Tactile : UX optimisée pour les tablettes et écrans tactiles industriels.",
                    "Multi-Livraison : Intégration unifiée d'Uber Eats, Glovo, Just Eat et propre livraison.",
                    "Facturation Légale : Émission de factures nominales, simplifiées et rapports Z.",
                    "Impression Intelligente : Système multi-imprimante (Cuisine/Bar) avec protocole ESC/POS.",
                    "Contrôle de Caisse : Paiements partiels, division de note et gestion des remises.",
                    "Déploiement All-in-One : Exécutable unique servant l'API, la BDD et le Web localement."
                ],
                stack: ["C#", ".NET 8", "React 19", "Vite", "TailwindCSS", "SQLite", "Entity Framework", "ESC/POS"]
            },
            p7_desc: "Système de point de vente (TPV) complet et Menu Numérique pour The Kebab Lab. Gestion des commandes en temps réel, KDS, administration avancée et déploiement automatisé.",
            p7_details: {
                title: "The Kebab Lab – TPV & Management Ecosystem",
                subtitle: "Solution de gestion 360° pour la restauration moderne",
                description: "Plateforme professionnelle conçue pour optimiser le cycle complet d'un restaurant. Basé sur l'écosystème Snack Tanger, adapté aux besoins spécifiques de The Kebab Lab.",
                features: [
                    "Gestion Tactile : UX optimisée pour les tablettes.",
                    "Multi-Livraison : Intégration de plateformes externes.",
                    "Facturation Légale : Rapports Z et tickets légaux.",
                    "Impression Intelligente : Système ESC/POS pour cuisine et bar."
                ],
                stack: [".NET", "React", "SQLite", "TailwindCSS", "Entity Framework", "ESC/POS", "GitHub"]
            },
            p8_desc: "Plateforme web d'entreprise et marketplace de licences VTC en Espagne. Gestion des licences (achat/vente), blog sectoriel et panneau admin sur /admin.",
            p8_details: {
                title: "GetVTC – Marketplace & Conseil VTC",
                subtitle: "Plateforme web d'entreprise et gestion de licences VTC",
                description: "Plateforme complète adaptée au secteur VTC en Espagne. Combine un site public avec marketplace d'achat/vente de licences et un panneau d'administration.",
                features: [
                    "Marketplace VTC: Gestion en temps réel des offres de licences.",
                    "Panneau Admin: Contrôle des leads, demandes et publications.",
                    "Contenu & Blog: Actualités du secteur et offres d'emploi.",
                    "Architecture Serverless: Déploiement Cloudflare Pages avec backend Supabase."
                ],
                stack: ["Next.js", "TypeScript", "PostgreSQL", "TailwindCSS", "Cloudflare", "GitHub"]
            },
            p9_desc: "Galerie web publique de photos culinaires générées par IA pour cartes numériques, kiosques TPV et marketing sans frais de stockage.",
            p9_details: {
                title: "FoodPix – Food Image Hub",
                subtitle: "Galerie de photographies culinaires IA",
                description: "Banque d'images haute résolution dédiée à la restauration. Permet d'obtenir des photos de nourriture gratuites et libres de droits pour menús et TPVs.",
                features: [
                    "Stockage Cloudflare R2: 10 Go d'images WebP servies à très haute vitesse.",
                    "Internationalisation: Support multilingue (ES/EN/FR).",
                    "Zéro Coût: Fonctionnement sur l'offre gratuite de Cloudflare.",
                    "Panneau Admin: Gestion du catalogue via Pages Functions."
                ],
                stack: ["React", "Vite", "TailwindCSS", "Cloudflare", "GitHub"]
            },
            p10_desc: "Système de réservation en ligne en temps réel pour salons de coiffure avec notifications Telegram Bot API et TPV intégré.",
            p10_details: {
                title: "R7Sultan – Réservations & TPV Coiffure",
                subtitle: "Plateforme de réservation en temps réel et TPV",
                description: "Système de réservation pour salons de coiffure. Garantit la disponibilité sans double réservation grâce aux contraintes PostgreSQL et notifie via Telegram.",
                features: [
                    "Contrôle de Disponibilité: Algorithme anti-double réservation.",
                    "Alertes Instantanées: Notifications automatiques Telegram Bot & Email.",
                    "Réservation Sans Compte: Lien unique de gestion du rendez-vous.",
                    "Panneau Admin & TPV: Suivi des rendez-vous et encaissements (Espèces/Carte/Bizum)."
                ],
                stack: ["Next.js", "TypeScript", "PostgreSQL", "TailwindCSS", "Cloudflare", "GitHub"]
            },
            p11_desc: "Site web public et panneau d'administration pour le restaurant Amigos2. Gestion interactive du menu numérique, promotions et galerie via Supabase.",
            p11_details: {
                title: "Amigos2 – Web & Admin Restauration",
                subtitle: "Plateforme web d'entreprise et panneau de gestion",
                description: "Solution React découplée permettant au restaurateur de gérer son menu, ses offres et sa galerie en toute autonomie.",
                features: [
                    "Menu Numérique: Catégories, plats, prix et allergènes.",
                    "Panneau de Gestion: Administration intuitive sur admin.amigos2.com.",
                    "Supabase Backend: Base de données PostgreSQL, auth et stockage.",
                    "Déploiement CD: Intégration continue sur Cloudflare Pages."
                ],
                stack: ["React", "Vite", "PostgreSQL", "TailwindCSS", "Cloudflare", "GitHub"]
            }
        },
        contact: { linkedin: "LinkedIn", email: "Email", github: "GitHub", whatsapp: "WhatsApp" },
        system: {
            cc: "Centre de Contrôle",
            battery: "Batterie",
            charging: "Chargement",
            config_battery: "Paramètres de la batterie...",
            wifi: "Wi-Fi",
            on: "Activé",
            known_networks: "Réseaux connus",
            wifi_settings: "Réglages Wi-Fi...",
            calendar: "Calendrier",
            brightness: "Luminosité",
            fullscreen: "Plein écran",
            download_cv: "Télécharger le CV",
            print_cv: "Imprimer le CV",
            about_title: "À propos de ce Portfolio",
            languages: "Langues",
            theme: "Thème",
            dark: "Sombre",
            light: "Clair",
            shortcuts_title: "Raccourcis Clavier",
            open_spotlight: "Ouvrir Spotlight",
            toggle_theme: "Changer le Thème",
            close_modals: "Fermer les modales",
            nav_spotlight: "Naviguer dans Spotlight",
            select_result: "Choisir le résultat",
            search_placeholder: "Rechercher dans le portfolio...",
            dark_mode: "Mode Sombre",
            light_mode: "Mode Clair",
            suggestions: "Suggestions",
            no_results: "Aucun résultat",
            curr_pdf: "Curriculum en PDF",
            main_section: "Section Principale",
            tpv_desc: "Système POS Intégral",
            date_settings: "Réglages Date et Heure...",
            native: "Maternel / Bilingue",
            prof_eng: "Compétence professionnelle",
            basic: "Connaissance de base",
            a1_level: "A1 Débutant"
        },
        menubar: {
            apple_about: "À propos de ce Portfolio",
            apple_pref: "Réglages Système...",
            file: "Fichier",
            edit: "Édition",
            view: "Présentation",
            go: "Aller",
            window: "Fenêtre",
            help: "Aide",
            copy_email: "Copier l'Email",
            copy_link: "Copier LinkedIn",
            copy_wa: "Copiar WhatsApp",
            shortcuts: "Raccourcis Clavier",
            open_windows: "Fenêtres Ouvertes",
            send_email: "Envoyer un Email"
        }
    },
    de: {
        nav: { home: "Startseite", projects: "Projekte", experience: "Erfahrung", skills: "Fähigkeiten", contact: "Kontakt" },
        hero: { title_prefix: "Hallo, ich bin", subtitle: "Spezialist für IT-Support und -Administration mit Erfahrung in Unternehmens- und öffentlichen Umgebungen. Ich verwalte Linux- und Windows-Systeme, Netzwerke, Microsoft 365, Hardware und Datenbanken und sorge für einen stabilen und effizienten Betrieb. Es motiviert mich, technische Probleme zu lösen und die Benutzererfahrung zu verbessern." },
        cta: { view: "Projekte ansehen", cv: "Lebenslauf herunterladen" },
        sections: { exp: "Erfahrung", sk: "Fähigkeiten", proj: "Projekte", contact: "Kontakt",
            exp_desc: "HIPRA · My Home Market · Ajuntament",
            sk_desc: "Netzwerk · Cloud · Dev · IA",
            proj_desc: "Snack Tanger · ERAY · Hotel",
            contact_desc: "LinkedIn · Email · GitHub"
        },
        exp: {
            e1_place: "Mai 2026 - Heute", e1_role: "IT Workplace Technician",
            e1_t1: "IT Procurement (SAP): Hardware-Einkauf, Angebotseinholung und PoC-Tests (Try & Buy).",
            e1_t2: "Industrieprojekte: Koordination von IT-Infrastruktur-Deployments in Produktionsstätten.",
            e1_t3: "Hardware & Leasing: Verwaltung der Apple/Dell-Flotte, Bereitstellung und Leasing-Verträge.",
            e1_t4: "AV-Lösungen: Betreuung von Videokonferenzräumen (Cisco Room Bar, Evoko) und Migration zu MS Teams.",
            e1_t5: "IT Onboarding & Sicherheit: Wöchentliche IT-Einführungssitzungen und Schulungen zur Cybersicherheit.",
            e1_t6: "Tagesgeschäft: L2-Support und Bearbeitung von Unternehmens- und Industrie-Tickets.",

            e2_place: "Juni 2025 - Mai 2026", e2_role: "IT Workplace Intern",
            e2_t1: "L2-Support & M365: Behebung komplexer Störungen und Verwaltung von Microsoft 365-Konten.",
            e2_t2: "Ticket-Systeme & Staging: Incident-Management (Remedy/SmartIT) und Staging von Laptops/IGEL-Clients.",
            e2_t3: "Mobilgeräte & Druck: Konfiguration von iOS/Android, Cisco VoIP und RFID-/Thermodruckern (Zebra/Honeywell).",
            e2_t4: "Sicherheit & Garantie: Lieferantenkoordination für Reparaturen und Einspielen von Sicherheits-Patches.",

            e3_place: "Juli 2020 - Juni 2025", e3_role: "Sales Assistant",
            e3_t1: "Kundenbetreuung: Individuelle Beratung, Bedarfsanalyse und Steigerung der Kundenzufriedenheit.",
            e3_t2: "Bestand & Kasse: Inventarkontrolle, Warennachbestellung und Abwicklung des Kassenbetriebs.",

            e4_place: "November 2023 – April 2024", e4_role: "IT Helpdesk Intern",
            e4_t1: "Kommunaler Support: Vor-Ort- und Remote-IT-Support für städtische Mitarbeiter.",
            e4_t2: "Systeme & Handbücher: Linux-Diagnose-Werkzeuge, Rechtevergabe und Erstellung von Anleitungen."
        },
        skills: {
            categories: {
                net: "Netztwerk & Sicherheit",
                sys: "Systeme & Workspace",
                cloud: "Cloud & DevOps",
                dev: "Entwicklung",
                db: "Datenbanken",
                hw: "Hardware & Support",
                ia: "KI & Automatisierung",
                prod: "Produktivität",
                langs: "Sprachen"
            },
            desc: {
                net: "Infrastruktur, Konnektivität und Netzwerksicherheit.",
                sys: "Betriebssystemadministration und Arbeitsumgebungen.",
                cloud: "Skalierbare Infrastruktur und Automatisierung.",
                dev: "Entwicklungssprachen und Tools.",
                db: "Big Data und strukturierte Datenverwaltung.",
                hw: "Außendienstunterstützung und virtuelle Umgebungen.",
                ia: "KI und Workflow-Optimierung mit n8n.",
                prod: "Projektmanagement und Zusammenarbeit.",
                langs: "Kommunikationsfähigkeit im globalen Umfeld."
            },
            items: {
                dns_desc: "Domain-Auflösung und -Verwaltung",
                dhcp_desc: "Dynamische IP und Subnetzverwaltung",
                pfsense_desc: "Grundlagen Firewall und Routing",
                cisco_desc: "IP-Telefone und Basisnetzwerke",
                grandstream_desc: "VoIP- und IP-Telefonie-Support",
                wireshark_desc: "Grundlegende Paketanalyse",
                linux_desc: "Serveradministration und Diagnose",
                windows_desc: "Server, AD und Benutzerunterstützung",
                m365_desc: "Tenant-Admin und Cloud-Apps",
                macos_desc: "Erweiterter Support und Expertennutzung",
                mdm_desc: "iOS- und Android-Flottenmanagement",
                shell_desc: "Grundlegendes Bash- und PowerShell-Scripting",
                azure_desc: "Grundlagen Azure und Entra ID",
                aws_desc: "Grundlagen EC2 und S3",
                docker_desc: "Container und grundlegende Bereitstellungen",
                k8s_desc: "Orchestrierung und Cluster-Skalierung",
                terraform_desc: "IaC-Grundlagen",
                cloudflare_desc: "WAF-Sicherheit and DNS-Performance",
                python_desc: "Backend, Scripting und FastAPI",
                js_desc: "Frontend (React) und Logik",
                react_desc: "Moderne Webschnittstellen und SPAs",
                fastapi_desc: "Hochleistungs-Python-APIs",
                tailwind_desc: "Modernes CSS-Webdesign",
                dotnet_desc: "Grundlegende C#- & .NET-Apps",
                htmlcss_desc: "Weblayout und Styling",
                csharp_desc: "Konsolen- und Systemanwendungen",
                git_desc: "Versionskontrolle und CI/CD",
                postgres_desc: "Relationale DB & Basic Admin",
                mysql_desc: "Relationales DB-Management",
                sqlite_desc: "Leichte DB für lokale Apps",
                mssql_desc: "Grundlegende SQL Server-Admin",
                nosql_desc: "JSON-Dokumentenverwaltung",
                zebra_desc: "Zebra-Drucker und RFID-Spezialist",
                honeywell_desc: "Hardware-Support für die Industrie",
                igel_desc: "Thin Clients und Workspace-Management",
                vmware_desc: "VMware- und VirtualBox-Umgebungen",
                vbox_desc: "Erweiterte lokale Virtualisierung",
                rpi_desc: "Embedded Systems und SBC",
                n8n_desc: "Erweiterte Workflow-Automatisierung",
                copilot_desc: "KI-gestützter Codierungsassistent",
                gemini_desc: "LLMs für die Produktivitätsnutzung",
                llm_desc: "GPT, Gemini und Prompt Engineering",
                teams_desc: "Unternehmenszusammenarbeit & Teams",
                office_desc: "Office 365 Enterprise-Admin",
                clickup_desc: "Aufgaben- und Projektmanagement",
                notion_desc: "Workspace und Dokumentation",
                jira_desc: "Fehlerverfolgung und Agile",
                ansible_desc: "Grundlegendes Konfigurationsmanagement",
                vlan_desc: "Grundlagen der Netzwerksegmentierung",
                ad_desc: "Domain- & Benutzerverwaltung (AD)",
                gpo_desc: "Gruppenrichtlinien & Sicherheit",
                parallels_desc: "macOS-Virtualisierung",
                actions_desc: "Bereitstellungsautomatisierung",
                oracle_desc: "Oracle DB Grundlagen",
                access_desc: "Relationale DBs mit Office",
                json_desc: "Datenstrukturen und APIs",
                rfid_desc: "Funkidentifikationssysteme",
                peri_desc: "Peripherie- und Scanner-Support",
                ollama_desc: "Lokale Ausführung von LLMs",
                prompt_desc: "KI-Abfrageoptimierung",
                excel_desc: "Excel & Datenmanagement",
                project_desc: "Grundlegende Projektplanung",
                german_desc: "Anfangskenntnisse",
                agents_desc: "KI-Agenten & LangChain",
                vector_desc: "Vektordatenbanken",
                image_desc: "KI-Bildgenerierung",
                redis_desc: "Cache & In-Memory-DB Grundlagen",
                diagnos_desc: "Fortgeschrittene HW-Diagnose",
                vite_desc: "Frontend-Tools der nächsten Generation",
                orm_desc: "Typsichere DB-Interaktionen",
                sharp_desc: "Hochleistungs-Bildverarbeitung",
                pages_desc: "Statische Hosting-Hochverfügbarkeit",
                lighthouse_desc: "SEO- und Leistungsoptimierung",
                python_fastapi: "Python / FastAPI",
                python_fastapi_desc: "Python Scripting & Basic Backend",
                js_react: "JavaScript / React",
                js_react_desc: "Frontend & grundlegende Logik",
                cicd: "CI/CD & Automatisierung",
                cicd_desc: "GitHub Actions & Hochverfügbares Hosting",
                sqlite_orm: "SQLite & SQLModel",
                sqlite_orm_desc: "Lokale BBDD & ORM-Mapping",
                zebra_rfid: "Zebra & RFID",
                zebra_rfid_desc: "Industrielle Drucker & RFID-Spezialist",
                honeywell_scan: "Honeywell Scanner",
                honeywell_scan_desc: "Industrielles Scannen & HW-Support",
                igel_new: "Thin Clients (IGEL)",
                igel_new_desc: "IGEL OS & Workspace-Management",
                vminfra: "VM-Infrastruktur",
                vminfra_desc: "VMware ESXi & VirtualBox Ops",
                hw_diag: "HW-Support & Diagnostik",
                hw_diag_desc: "Fortgeschrittene Peripheriegeräte & HW-Fehlerbehebung",
                n8n_new: "n8n-Automatisierung",
                n8n_new_desc: "Grundlegende Workflow-Automatisierung",
                chatgpt_new: "ChatGPT",
                chatgpt_new_desc: "Experten-LLM-Prompting & Analyse",
                claude_new: "Claude / Claude Code",
                claude_new_desc: "Fortgeschrittene Argumentation & CLI-Tools",
                openclaw_new: "OpenClaw",
                openclaw_new_desc: "Autonome KI-Agenten",
                nanobanana_new: "Nano Banana Pro",
                nanobanana_new_desc: "Professionelle Bilderzeugung",
                openai_new: "OpenAI / GPT",
                openai_new_desc: "LLM-Nutzung & Prompting"
            }
        },
        projects: {
            p1_desc: "Portfolio im iOS26-Design mit HTML, CSS & JS. Dunkel-/Hellmodus, Sprachauswahl und Dynamic Island.",
            p2_desc: "Hotelmanagement-App mit Python + PostgreSQL. Buchungen, Benutzerverwaltung, Replikation und automatische Backups.",
            p3_desc: "Action-Slasher mit 3 Gegner-Typen und Charakter-Upgrades. Entwickelt mit Unity.",
            p4_desc: "2D-Space-Shooter mit Power-Ups, Punktesystem und Gegnerwellen. Entwickelt mit Unity.",
            p5_desc: "On-Premise-Ökosystem (.NET 8 & React 19) für die taktile Restaurantverwaltung. Bestellkontrolle, Multi-Küchendruck, Lieferung und Abrechnung.",
            p5_details: {
                title: "Snack Tanger 303 – POS & Management Ecosystem",
                subtitle: "360°-Management-Lösung für moderne Restaurants",
                description: "Professionelle Plattform zur Optimierung des gesamten Restaurantzyklus. Von der taktilen Bestellung bis zum Kassenabschluss gewährleistet das System einen stabilen Betrieb ohne Cloud-Abhängigkeit.",
                features: [
                    "Taktile Verwaltung: Optimierte UX für Tablets und Industrie-Touchscreens.",
                    "Multi-Delivery: Integration von Uber Eats, Glovo, Just Eat und eigenem Versand.",
                    "Rechnungsstellung: Ausstellung von Rechnungen und Z-Berichten nach geltendem Recht.",
                    "Smart Printing: Multi-Drucker-System (Küche/Bar) mit ESC/POS-Protokoll.",
                    "Kassenkontrolle: Teilzahlungen, Rechnungstrennung und Rabattverwaltung.",
                    "All-in-One Deployment: Einzelne EXE-Datei für API, DB und Web lokal."
                ],
                stack: ["C#", ".NET 8", "React 19", "Vite", "TailwindCSS", "SQLite", "Entity Framework", "ESC/POS"]
            },
            p7_desc: "Integriertes Kassensystem (POS) und digitale Speisekarte für The Kebab Lab. Echtzeit-Bestellverwaltung, KDS, erweiterte Administration und automatisierte Bereitstellung.",
            p7_details: {
                title: "The Kebab Lab – POS & Management Ecosystem",
                subtitle: "360°-Management-Lösung für moderne Restaurants",
                description: "Professionelle Plattform zur Optimierung des gesamten Restaurantzyklus. Basiert auf dem Snack Tanger-Ökosystem, angepasst an die Anforderungen von The Kebab Lab.",
                features: [
                    "Taktile Verwaltung: Optimierte UX für Tablets.",
                    "Multi-Delivery: Integration externer Lieferplattformen.",
                    "Rechnungsstellung: Z-Berichte und gesetzliche Belege.",
                    "Smart Printing: ESC/POS-System für Küche und Bar."
                ],
                stack: [".NET", "React", "SQLite", "TailwindCSS", "Entity Framework", "ESC/POS", "GitHub"]
            },
            p8_desc: "Unternehmenswebseite und VTC-Lizenz-Marketplace in Spanien. Beinhaltet Lizenzverwaltung (Kauf/Verkauf), Branchenblog und Admin-Dashboard unter /admin.",
            p8_details: {
                title: "GetVTC – Marketplace & VTC-Beratung",
                subtitle: "Unternehmens-Webplattform & VTC-Lizenzverwaltung",
                description: "Umfassende Plattform für den VTC-Sektor in Spanien. Kombiniert eine öffentliche Website mit Lizenz-Marketplace und privatem Admin-Dashboard.",
                features: [
                    "VTC Marketplace: Echtzeitverwaltung von Lizenzangeboten.",
                    "Admin-Dashboard: Kontrolle von Leads, Anfragen und Beiträgen.",
                    "Blog & Inhalte: Branchennews und Stellenangebote.",
                    "Serverless-Architektur: Cloudflare Pages-Deployment mit Supabase-Backend."
                ],
                stack: ["Next.js", "TypeScript", "PostgreSQL", "TailwindCSS", "Cloudflare", "GitHub"]
            },
            p9_desc: "Öffentliche Webgalerie für KI-generierte Food-Fotografie für digitale Speisekarten, Kassensysteme und Marketing ohne Speicherkosten.",
            p9_details: {
                title: "FoodPix – Food Image Hub",
                subtitle: "Galerie für KI-generierte Food-Fotografie",
                description: "Hochauflösende Bilddatenbank für die Gastronomie. Ermöglicht Restaurantbesitzern und Entwicklern den Zugriff auf lizenzfreie Essensfotos.",
                features: [
                    "Cloudflare R2 Storage: 10 GB WebP-Bilder rasend schnell serviert.",
                    "Internationalisierung: Mehrsprachige Unterstützung (ES/EN/FR).",
                    "Null Kosten: Vollständiger Betrieb im kostenlosen Cloudflare-Tarif.",
                    "Admin-Panel: Katalogverwaltung über Pages Functions."
                ],
                stack: ["React", "Vite", "TailwindCSS", "Cloudflare", "GitHub"]
            },
            p10_desc: "Echtzeit-Online-Buchungssystem für Friseursalons mit automatischen Benachrichtigungen über Telegram Bot API und integriertem Kassensystem.",
            p10_details: {
                title: "R7Sultan – Friseur-Buchung & POS",
                subtitle: "Echtzeit-Buchungsplattform & Kassensystem",
                description: "Buchungssystem der nächsten Generation für Friseursalons. Garantiert überschneidungsfreie Terminvergabe und benachrichtigt Friseure sofort via Telegram.",
                features: [
                    "Verfügbarkeitskontrolle: Anti-Doppelbuchungs-Algorithmus auf Datenbankebene.",
                    "Sofortige Benachrichtigungen: Automatische Telegram Bot- und E-Mail-Hinweise.",
                    "Gast-Buchung: Terminverwaltung über eindeutigen Token ohne Registrierung.",
                    "Admin- & POS-Panel: Verwaltung von Terminen, Arbeitszeiten und Kassenabrechnung."
                ],
                stack: ["Next.js", "TypeScript", "PostgreSQL", "TailwindCSS", "Cloudflare", "GitHub"]
            },
            p11_desc: "Öffentliche Website und Admin-Panel für das Restaurant Amigos2. Interaktive digitale Speisekarte, Aktionen und Galerie powered by Supabase.",
            p11_details: {
                title: "Amigos2 – Restaurant Web & Admin",
                subtitle: "Unternehmens-Webplattform & Management-Panel",
                description: "Entkoppelte duale React-Lösung, die es dem Inhaber ermöglicht, Speisekarte, Aktionen und Fotos selbstständig zu verwalten.",
                features: [
                    "Digitale Speisekarte: Kategorien, Produkte, Preise und Allergene.",
                    "Management-Panel: Intuitive Verwaltung unter admin.amigos2.com.",
                    "Supabase-Backend: PostgreSQL-Datenbank, Auth und Medien-Speicher.",
                    "CD-Deployment: Kontinuierliche Integration auf Cloudflare Pages."
                ],
                stack: ["React", "Vite", "PostgreSQL", "TailwindCSS", "Cloudflare", "GitHub"]
            }
        },
        contact: { linkedin: "LinkedIn", email: "E-Mail", github: "GitHub", whatsapp: "WhatsApp" },
        system: {
            cc: "Kontrollzentrum",
            battery: "Batterie",
            charging: "Laden",
            config_battery: "Batterieeinstellungen...",
            wifi: "Wi-Fi",
            on: "Ein",
            known_networks: "Bekannte Netzwerke",
            wifi_settings: "Wi-Fi-Einstellungen...",
            calendar: "Kalender",
            brightness: "Helligkeit",
            fullscreen: "Vollbild",
            download_cv: "Lebenslauf herunterladen",
            print_cv: "Lebenslauf drucken",
            about_title: "Über dieses Portfolio",
            languages: "Sprachen",
            theme: "Thema",
            dark: "Dunkel",
            light: "Hell",
            shortcuts_title: "Tastaturkürzel",
            open_spotlight: "Spotlight öffnen",
            toggle_theme: "Thema umschalten",
            close_modals: "Modale schließen",
            nav_spotlight: "In Spotlight navigieren",
            select_result: "Ergebnis auswählen",
            search_placeholder: "Im Portfolio suchen...",
            dark_mode: "Dunkelmodus",
            light_mode: "Hellmodus",
            suggestions: "Vorschläge",
            no_results: "Keine Ergebnisse",
            curr_pdf: "Lebenslauf als PDF",
            main_section: "Hauptbereich",
            tpv_desc: "Komplettes POS-System",
            date_settings: "Datum & Uhrzeit Einstellungen...",
            native: "Muttersprachlich / Bilingual",
            prof_eng: "Berufliche Kompetenz",
            basic: "Grundkenntnisse",
            a1_level: "A1 Anfänger"
        },
        menubar: {
            apple_about: "Über dieses Portfolio",
            apple_pref: "Systemeinstellungen...",
            file: "Ablage",
            edit: "Bearbeiten",
            view: "Darstellung",
            go: "Gehe zu",
            window: "Fenster",
            help: "Hilfe",
            copy_email: "E-Mail kopieren",
            copy_link: "LinkedIn kopieren",
            copy_wa: "WhatsApp kopieren",
            shortcuts: "Tastaturkurzbefehle",
            open_windows: "Offene Fenster",
            send_email: "E-Mail senden"
        }
    }
};
