const I18N = {
    es: {
        nav: { home: "Inicio", projects: "Proyectos", experience: "Experiencia", skills: "Habilidades", contact: "Contacto" },
        hero: { title_prefix: "Hola, soy", subtitle: "Especialista en soporte y administración IT, con experiencia en entornos corporativos y públicos. Gestiono sistemas Linux y Windows, redes, Microsoft 365, hardware y bases de datos, asegurando operaciones estables y eficientes. Me motiva resolver incidencias técnicas y mejorar la experiencia del usuario." },
        cta: { view: "Ver proyectos", cv: "Descargar CV" },
        sections: { exp: "Experiencia", sk: "Habilidades", proj: "Proyectos", contact: "Contacto",
            exp_desc: "HIPRA · Ajuntament",
            sk_desc: "Redes · Cloud · Dev · IA",
            proj_desc: "Snack Tanger · ERAY · Hotel",
            contact_desc: "LinkedIn · Email · GitHub"
        },
        exp: {
            e1_place: "Junio 2025 - Presente", e1_role: "IT Workplace Intern",
            e1_t1: "Soporte técnico de segundo nivel (hardware, software y conectividad).",
            e1_t2: "Gestión de incidencias mediante Remedy y SmartIT.",
            e1_t3: "Preparación y despliegue de equipos (portátiles, IGEL, periféricos).",
            e1_t4: "Configuración de móviles iOS/Android, teléfonos Cisco y escáneres.",
            e1_t5: "Impresoras RFID y térmicas (Zebra, Honeywell).",
            e1_t6: "Gestión de garantías y reparaciones con proveedores.",
            e1_t7: "Colaboración en seguridad, parches y actualizaciones.",
            e2_place: "Noviembre 2023 – Abril 2024", e2_role: "IT Helpdesk Intern",
            e2_t1: "Soporte técnico presencial y remoto para personal municipal.",
            e2_t2: "Instalación y mantenimiento de equipos y periféricos.",
            e2_t3: "Administración básica de sistemas y permisos de usuario.",
            e2_t4: "Herramientas Linux para diagnóstico y resolución de fallos.",
            e2_t5: "Documentación de procedimientos y guías de usuario.",
            e2_t6: "Preparación y despliegue de equipos."
        },
        skills: {
            categories: {
                net: "Redes & Seguridad",
                sys: "Sistemas & Workspace",
                cloud: "Cloud & DevOps",
                dev: "Desarrollo",
                db: "Bases de Datos",
                hw: "Hardware & Support",
                ia: "IA & Automatización",
                prod: "Productividad",
                langs: "Idiomas"
            },
            desc: {
                net: "Infraestructura, conectividad y seguridad de red.",
                sys: "Sistemas operativos y entornos de trabajo.",
                cloud: "Infraestructura escalable y automatización.",
                dev: "Lenguajes y herramientas de desarrollo.",
                db: "Gestión de datos masivos y estructurados.",
                hw: "Soporte de campo y entornos virtuales.",
                ia: "IA y optimización de flujos con n8n.",
                prod: "Gestión de proyectos y colaboración.",
                langs: "Comunicación en entornos globales."
            },
            items: {
                dns_desc: "Resolución y gestión de dominios",
                dhcp_desc: "IP dinámica y gestión de subredes",
                pfsense_desc: "Fundamentos de Firewall y Routing",
                cisco_desc: "Teléfonos IP y Redes Básicas",
                grandstream_desc: "Soporte de VoIP y Telefonía IP",
                wireshark_desc: "Análisis Básico de Paquetes",
                linux_desc: "Admin de servidores y diagnóstico",
                windows_desc: "Servidores, AD y soporte a usuarios",
                m365_desc: "Admin de Tenant y Apps Cloud",
                macos_desc: "Soporte y uso avanzado",
                mdm_desc: "Gestión de flotas iOS y Android",
                shell_desc: "Scripting Básico en Bash y PowerShell",
                azure_desc: "Fundamentos de Azure y Entra ID",
                aws_desc: "Conceptos Básicos de EC2 y S3",
                docker_desc: "Contenedores y Despliegues Básicos",
                k8s_desc: "Orquestación y escalado de clusters",
                terraform_desc: "Fundamentos de IaC",
                cloudflare_desc: "Seguridad WAF y rendimiento DNS",
                python_desc: "Backend, Scripting y FastAPI",
                js_desc: "Frontend (React) y Lógica",
                react_desc: "Interfaces web modernas y SPA",
                fastapi_desc: "APIs de alto rendimiento con Python",
                tailwind_desc: "Diseño web con CSS moderno",
                dotnet_desc: "C# y Aplicaciones .NET Básicas",
                htmlcss_desc: "Maquetación y estilos web",
                csharp_desc: "Aplicaciones de consola y sistema",
                git_desc: "Control de versiones y CI/CD",
                postgres_desc: "BD Relacional y Admin Básica",
                mysql_desc: "Gestión de BBDD Relacionales",
                sqlite_desc: "BBDD ligera para apps locales",
                mssql_desc: "Admin Básica de SQL Server",
                nosql_desc: "Gestión de documentos JSON",
                zebra_desc: "Impresoras Zebra e RFID especialista",
                honeywell_desc: "Soporte hardware industrial",
                igel_desc: "Thin Clients y Gestión Workspace",
                vmware_desc: "Entornos VMware y VirtualBox",
                vbox_desc: "Virtualización local avanzada",
                rpi_desc: "Sistemas embebidos y SBC",
                n8n_desc: "Automatización avanzada de flujos",
                copilot_desc: "Asistente IA para codificación",
                gemini_desc: "Uso de LLMs para productividad",
                llm_desc: "GPT, Gemini y Prompt Engineering",
                teams_desc: "Colaboración corporativa y Teams",
                office_desc: "Admin de aplicaciones Office 365",
                clickup_desc: "Gestión de tareas y proyectos",
                notion_desc: "Espacio de trabajo y documentación",
                jira_desc: "Gestión de incidencias y Agile",
                ansible_desc: "Gestión Básica de Configuración",
                vlan_desc: "Fundamentos de Segmentación de Red",
                ad_desc: "Gestión de dominios y usuarios AD",
                gpo_desc: "Políticas de grupo y seguridad",
                parallels_desc: "Virtualización en macOS",
                actions_desc: "Automatización de despliegues",
                oracle_desc: "Fundamentos de Oracle DB",
                access_desc: "BBDD relacionales con Office",
                json_desc: "Estructuras de datos y APIs",
                rfid_desc: "Sistemas de identificación por radio",
                peri_desc: "Soporte a periféricos y escáneres",
                ollama_desc: "Ejecución de LLMs en local",
                prompt_desc: "Optimización de consultas a IA",
                excel_desc: "Excel y Gestión de Datos",
                project_desc: "Planificación Básica de Proyectos",
                german_desc: "Conocimientos iniciales",
                agents_desc: "IA Agentes y LangChain",
                vector_desc: "Bases de datos Vectoriales",
                image_desc: "Generación de imágenes IA",
                redis_desc: "Caché y BD en Memoria Básica",
                diagnos_desc: "Diagnóstico avanzado de HW",
                vite_desc: "Herramientas de frontend rápidas",
                orm_desc: "Interacciones seguras con BBDD",
                sharp_desc: "Procesamiento de imágenes",
                pages_desc: "Hosting estático de alta disponibilidad",
                lighthouse_desc: "Optimización de SEO y rendimiento",
                python_fastapi: "Python / FastAPI",
                python_fastapi_desc: "Scripting en Python y Backend Básico",
                js_react: "JavaScript / React",
                js_react_desc: "Frontend y Lógica Básica",
                cicd: "CI/CD & Automatización",
                cicd_desc: "GitHub Actions y Hosting d'alta disp.",
                sqlite_orm: "SQLite & SQLModel",
                sqlite_orm_desc: "BBDD locales y Mapeo ORM",
                zebra_rfid: "Zebra & RFID",
                zebra_rfid_desc: "Impresoras industriales y Especialista RFID",
                honeywell_scan: "Escáneres Honeywell",
                honeywell_scan_desc: "Escaneo industrial y Soporte de Hardware",
                vminfra: "Infraestructura VM",
                vminfra_desc: "VMware ESXi y Operaciones VirtualBox",
                hw_diag: "Soporte HW & Diagnóstico",
                hw_diag_desc: "Periféricos avanzados y Resolución de averías",
                claude_code: "Claude / Claude Code",
                claude_code_desc: "Razonamiento avanzado y Herramientas CLI",
                openclaw: "OpenClaw",
                openclaw_desc: "Agentes de IA Autónomos",
                nanobanana: "Nano Banana Pro",
                nanobanana_desc: "Generación de Imágenes Profesional",
                openai_new: "OpenAI / GPT",
                openai_new_desc: "Uso de LLMs y Prompting",
                n8n_new: "Automatización n8n",
                n8n_new_desc: "Automatización Básica de Flujos"
            }
        },
        projects: {
            p1_desc: "Portafolio inspirado en iOS26 con HTML, CSS y JS. Modo oscuro/claro, selector de idioma y Dynamic Island como navegación.",
            p2_desc: "Aplicación de gestión hotelera con Python + PostgreSQL. Reservas, usuarios, seguridad, replicación y backups automáticos.",
            p3_desc: "Juego de acción con tres tipos de enemigos y mejoras de personaje. Hecho en Unity.",
            p4_desc: "Shooter 2D con power-ups, sistema de puntuación y oleadas. Hecho en Unity.",
            p5_desc: "Sistema TPV integral para restaurantes. Gestión de pedidos en tiempo real, pantalla de cocina (KDS), panel de administración y despliegue automático. Stack: Python (FastAPI), React y PostgreSQL.",
            p6_desc: "Carta digital estática sincronizada con el TPV local. Optimizada para móviles (QR), SEO y carga instantánea. Multiidioma y responsive."
        },
        contact: { linkedin: "LinkedIn", email: "Email", github: "GitHub", whatsapp: "WhatsApp" },
        system: {
            cc: "Centro de Control",
            battery: "Batería",
            charging: "Cargando",
            config_battery: "Configuración de la batería...",
            wifi: "Wi-Fi",
            on: "Activado",
            known_networks: "Redes conocidas",
            wifi_settings: "Ajustes de Wi-Fi...",
            calendar: "Calendario",
            brightness: "Brillo",
            fullscreen: "Pantalla completa",
            download_cv: "Descargar CV",
            print_cv: "Imprimir CV",
            about_title: "Acerca de este Portfolio",
            languages: "Idiomas",
            theme: "Tema",
            dark: "Oscuro",
            light: "Claro",
            shortcuts_title: "Atajos de Teclado",
            open_spotlight: "Abrir Spotlight",
            toggle_theme: "Toggle Tema",
            close_modals: "Cerrar modales",
            nav_spotlight: "Navegar en Spotlight",
            select_result: "Seleccionar resultado",
            search_placeholder: "Buscar en el portfolio...",
            dark_mode: "Modo Oscuro",
            light_mode: "Modo Claro",
            suggestions: "Sugerencias",
            no_results: "Sin resultados",
            curr_pdf: "Currículum en PDF",
            date_settings: "Configuración de fecha y hora...",
            native: "Nativo / Bilingüe",
            prof_eng: "Competencia profesional",
            basic: "Conocimiento básico",
            a1_level: "Nivel Inicial A1"
        },
        menubar: {
            apple_about: "Acerca de este Portfolio",
            apple_pref: "Ajustes del Sistema...",
            file: "Archivo",
            edit: "Edición",
            view: "Visualización",
            go: "Ir",
            window: "Ventana",
            help: "Ayuda",
            copy_email: "Copiar Email",
            copy_link: "Copiar LinkedIn",
            copy_wa: "Copiar WhatsApp",
            shortcuts: "Atajos de Teclado",
            open_windows: "Ventanas Abiertas",
            send_email: "Enviar un Email"
        }
    },
    en: {
        nav: { home: "Home", projects: "Projects", experience: "Experience", skills: "Skills", contact: "Contact" },
        hero: { title_prefix: "Hi, I'm", subtitle: "IT support and administration specialist with experience in corporate and public environments. I manage Linux and Windows systems, networks, Microsoft 365, hardware, and databases, ensuring stable and efficient operations. I am motivated by resolving technical issues and improving the user experience." },
        cta: { view: "View projects", cv: "Download CV" },
        sections: { exp: "Experience", sk: "Skills", proj: "Projects", contact: "Contact",
            exp_desc: "HIPRA · Ajuntament",
            sk_desc: "Network · Cloud · Dev · IA",
            proj_desc: "Snack Tanger · ERAY · Hotel",
            contact_desc: "LinkedIn · Email · GitHub"
        },
        exp: {
            e1_place: "Jun 2025 - Present", e1_role: "IT Workplace Intern",
            e1_t1: "L2 support for hardware, software and connectivity.",
            e1_t2: "Incident management via Remedy and ClickUp.",
            e1_t3: "Staging and deployment of laptops, IGEL and peripherals.",
            e1_t4: "iOS/Android mobiles, Cisco phones and scanners setup.",
            e1_t5: "RFID and thermal printers (Zebra, Honeywell).",
            e1_t6: "Warranty and repair management with vendors.",
            e1_t7: "Collaboration on security, patching and updates.",
            e2_place: "Nov 2023 – Apr 2024", e2_role: "IT Helpdesk Intern",
            e2_t1: "On-site and remote tech support for municipal staff.",
            e2_t2: "Equipment and peripheral installation and maintenance.",
            e2_t3: "Basic systems admin and user permissions.",
            e2_t4: "Linux tools for fault diagnosis and resolution.",
            e2_t5: "Process documentation and user guides.",
            e2_t6: "Staging and deployment of devices."
        },
        skills: {
            categories: {
                net: "Networks & Security",
                sys: "Systems & Workspace",
                cloud: "Cloud & DevOps",
                dev: "Development",
                db: "Databases",
                hw: "Hardware & Support",
                ia: "AI & Automation",
                prod: "Productivity",
                langs: "Languages"
            },
            desc: {
                net: "Infrastructure, connectivity and network security.",
                sys: "Operating systems and work environments.",
                cloud: "Scalable infrastructure and automation.",
                dev: "Development languages and tools.",
                db: "Big data and structured data management.",
                hw: "Field support and virtual environments.",
                ia: "AI and workflow optimization with n8n.",
                prod: "Project management and collaboration.",
                langs: "Communication in global environments."
            },
            items: {
                dns_desc: "Domain resolution and management",
                dhcp_desc: "Dynamic IP and subnet management",
                pfsense_desc: "Firewall & Routing Basics",
                cisco_desc: "IP Phones & Basic Networking",
                grandstream_desc: "VoIP and IP Telephony Support",
                wireshark_desc: "Basic Packet Analysis",
                linux_desc: "Server administration and diagnostics",
                windows_desc: "Servers, AD and user support",
                m365_desc: "Tenant Admin and Cloud Apps",
                macos_desc: "Advanced support and expert use",
                mdm_desc: "iOS and Android fleet management",
                shell_desc: "Basic Bash & PowerShell Scripting",
                azure_desc: "Azure & Entra ID Fundamentals",
                aws_desc: "EC2 & S3 Basics",
                docker_desc: "Containers & Basic Deployments",
                k8s_desc: "Orchestration and cluster scaling",
                terraform_desc: "IaC Fundamentals",
                cloudflare_desc: "WAF security and DNS performance",
                python_desc: "Backend, Scripting and FastAPI",
                js_desc: "Frontend (React) and Logic",
                react_desc: "Modern web interfaces and SPAs",
                fastapi_desc: "High-performance Python APIs",
                tailwind_desc: "Modern CSS web design",
                dotnet_desc: "Basic C# & .NET Apps",
                htmlcss_desc: "Web layout and styling",
                csharp_desc: "Console and system applications",
                git_desc: "Version control and CI/CD",
                postgres_desc: "Relational DB & Basic Admin",
                mysql_desc: "Relational DB management",
                sqlite_desc: "Lightweight DB for local apps",
                mssql_desc: "Basic SQL Server Admin",
                nosql_desc: "JSON document management",
                zebra_desc: "Zebra printers and RFID specialist",
                honeywell_desc: "Industrial hardware support",
                igel_desc: "Thin Clients and Workspace Management",
                vmware_desc: "VMware and VirtualBox environments",
                vbox_desc: "Advanced local virtualization",
                rpi_desc: "Embedded systems and SBC",
                n8n_desc: "Advanced workflow automation",
                copilot_desc: "AI-powered coding assistant",
                gemini_desc: "LLMs for productivity use",
                llm_desc: "GPT, Gemini and Prompt Engineering",
                teams_desc: "Corporate collaboration & Teams",
                office_desc: "Office 365 apps administration",
                clickup_desc: "Task and project management",
                notion_desc: "Workspace and documentation",
                jira_desc: "Issue tracking and Agile",
                ansible_desc: "Basic Configuration Management",
                vlan_desc: "Network Segmentation Fundamentals",
                ad_desc: "Domain & User Management (AD)",
                gpo_desc: "Group Policies & Security",
                parallels_desc: "macOS Virtualization",
                actions_desc: "Deployment Automation",
                oracle_desc: "Oracle DB Fundamentals",
                access_desc: "Relational DBs with Office",
                json_desc: "Data structures & APIs",
                rfid_desc: "Radio-Frequency ID Systems",
                peri_desc: "Peripherals & Scanner Support",
                ollama_desc: "Running local LLMs",
                prompt_desc: "AI Query Optimization",
                excel_desc: "Excel & Data Management",
                project_desc: "Basic Project Planning",
                german_desc: "Initial knowledge",
                agents_desc: "AI Agents & LangChain",
                vector_desc: "Vector Databases",
                image_desc: "AI Image Generation",
                redis_desc: "Cache & In-memory DB Basics",
                diagnos_desc: "Advanced HW Diagnosis",
                vite_desc: "Next-gen frontend tooling",
                orm_desc: "Type-safe DB interactions",
                sharp_desc: "High-performance image processing",
                pages_desc: "High-availability static hosting",
                lighthouse_desc: "SEO & performance audit",
                python_fastapi: "Python / FastAPI",
                python_fastapi_desc: "Python Scripting & Basic Backend",
                js_react: "JavaScript / React",
                js_react_desc: "Frontend & Basic Logic",
                cicd: "CI/CD & Automation",
                cicd_desc: "GitHub Actions & High-availability Hosting",
                sqlite_orm: "SQLite & SQLModel",
                sqlite_orm_desc: "Local DBs & ORM Mapping",
                zebra_rfid: "Zebra & RFID",
                zebra_rfid_desc: "Industrial Printers & RFID Specialist",
                honeywell_scan: "Honeywell Scanners",
                honeywell_scan_desc: "Industrial Scanning & HW Support",
                igel_new: "Thin Clients (IGEL)",
                igel_new_desc: "IGEL OS & Workspace Management",
                vminfra: "VM Infrastructure",
                vminfra_desc: "VMware ESXi & VirtualBox Ops",
                hw_diag: "HW Support & Diagnostics",
                hw_diag_desc: "Advanced Peripherals & HW Troubleshooting",
                n8n_new: "n8n Automation",
                n8n_new_desc: "Basic Workflow Automation",
                chatgpt_new: "ChatGPT",
                chatgpt_new_desc: "Expert LLM Prompting & Analysis",
                claude_new: "Claude / Claude Code",
                claude_new_desc: "Advanced Reasoning & CLI Tools",
                openclaw_new: "OpenClaw",
                openclaw_new_desc: "Autonomous AI Agents",
                nanobanana_new: "Nano Banana Pro",
                nanobanana_new_desc: "Professional Image Generation",
                openai_new: "OpenAI / GPT",
                openai_new_desc: "LLM Usage & Prompting"
            }
        },
        projects: {
            p1_desc: "Personal portfolio inspired by the iOS26 interface, developed with HTML, CSS, and JavaScript. Presents professional experience, skills, and projects in a modern and responsive design. Includes dark/light mode, language selection, and an interactive ‘Dynamic Island’ for navigation.",
            p2_desc: "Complete application for the integral management of a hotel chain. Includes control of reservations, customers, staff, services, and data auditing. Developed in Python (Tkinter) with a PostgreSQL database, it incorporates security, high availability, replication, automated backups, and exports in JSON/PDF.",
            p3_desc: "Action game set in the 18th century, starring ERAY, a character with magical abilities to defend his home. Includes three types of enemies with different attacks and items that improve the player's statistics. Developed with Unity, available in free executable format.",
            p4_desc: "2D action game developed with Unity, where players control a spaceship that must face waves of enemies. The game includes power-ups and upgrades for the ship, as well as a scoring system based on survival and enemy destruction. Available in free executable format.",
            p5_desc: "Comprehensive POS system for restaurants. Real-time order management, Kitchen Display System (KDS), admin dashboard, and automated deployment. Stack: Python (FastAPI), React, and PostgreSQL.",
            p6_desc: "High-performance static digital menu synced with the local POS. Optimized for mobile (QR), SEO, and instant loading. Multi-language and responsive design."
        },
        contact: { linkedin: "LinkedIn", email: "Email", github: "GitHub", whatsapp: "WhatsApp" },
        system: {
            cc: "Control Center",
            battery: "Battery",
            charging: "Charging",
            config_battery: "Battery Settings...",
            wifi: "Wi-Fi",
            on: "On",
            known_networks: "Known Networks",
            wifi_settings: "Wi-Fi Settings...",
            calendar: "Calendar",
            brightness: "Brightness",
            fullscreen: "Fullscreen",
            download_cv: "Download CV",
            print_cv: "Print CV",
            about_title: "About This Portfolio",
            languages: "Languages",
            theme: "Theme",
            dark: "Dark",
            light: "Light",
            shortcuts_title: "Keyboard Shortcuts",
            open_spotlight: "Open Spotlight",
            toggle_theme: "Toggle Theme",
            close_modals: "Close modals",
            nav_spotlight: "Navigate in Spotlight",
            select_result: "Select result",
            search_placeholder: "Search in portfolio...",
            dark_mode: "Dark Mode",
            light_mode: "Light Mode",
            suggestions: "Suggestions",
            no_results: "No results",
            curr_pdf: "Curriculum in PDF",
            main_section: "Main Section",
            tpv_desc: "Integral POS System",
            date_settings: "Date & Time Settings...",
            native: "Native / Bilingual",
            prof_eng: "Professional Proficiency",
            basic: "Basic Knowledge",
            a1_level: "A1 Beginner"
        },
        menubar: {
            apple_about: "About This Portfolio",
            apple_pref: "System Settings...",
            file: "File",
            edit: "Edit",
            view: "View",
            go: "Go",
            window: "Window",
            help: "Help",
            copy_email: "Copy Email",
            copy_link: "Copy LinkedIn",
            copy_wa: "Copy WhatsApp",
            shortcuts: "Keyboard Shortcuts",
            open_windows: "Open Windows",
            send_email: "Send an Email"
        }
    },
    ca: {
        nav: { home: "Inici", projects: "Projectes", experience: "Experiència", skills: "Habilitats", contact: "Contacte" },
        hero: { title_prefix: "Hola, sóc", subtitle: "Especialista en suport i administració IT, amb experiència en entorns corporatius i públics. Gestiono sistemes Linux i Windows, xarxes, Microsoft 365, maquinari i bases de dades, assegurant operacions estables i eficients. Em motiva resoldre incidències tècniques i millorar l'experiència de l'usuari." },
        cta: { view: "Veure projectes", cv: "Descarregar CV" },
        sections: { exp: "Experiència", sk: "Habilitats", proj: "Projectes", contact: "Contacte",
            exp_desc: "HIPRA · Ajuntament",
            sk_desc: "Xarxes · Cloud · Dev · IA",
            proj_desc: "Snack Tanger · ERAY · Hotel",
            contact_desc: "LinkedIn · Email · GitHub"
        },
        exp: {
            e1_place: "Juny 2025 - Present", e1_role: "IT Workplace Intern",
            e1_t1: "Suport tècnic de segon nivell (maquinari, programari i connectivitat).",
            e1_t2: "Gestió d'incidències mitjançant Remedy i SmartIT.",
            e1_t3: "Preparació i desplegament d'equips (portàtils, IGEL, perifèrics).",
            e1_t4: "Configuració d'iOS/Android, telèfons Cisco i escàners.",
            e1_t5: "Impressora RFID i tèrmiques (Zebra, Honeywell).",
            e1_t6: "Gestió de garanties i reparacions amb proveïdors.",
            e1_t7: "Col·laboració en seguretat, pàtching i actualitzacions.",
            e2_place: "Nov 2023 – Abr 2024", e2_role: "IT Helpdesk Intern",
            e2_t1: "Suport tècnic presencial i remot per a personal municipal.",
            e2_t2: "Instal·lació i manteniment d'equips i perifèrics.",
            e2_t3: "Administració bàsica i permisos d'usuari.",
            e2_t4: "Eines Linux per a diagnòstic i resolució d'avaries.",
            e2_t5: "Documentació de procediments i guies d'usuari.",
            e2_t6: "Preparació i desplegament d'equips."
        },
        skills: {
            categories: {
                net: "Xarxes & Seguretat",
                sys: "Sistemes & Workspace",
                cloud: "Cloud & DevOps",
                dev: "Desenvolupament",
                db: "Bases de Dades",
                hw: "Maquinari & Support",
                ia: "IA & Automatització",
                prod: "Productivitat",
                langs: "Idiomes"
            },
            desc: {
                net: "Infraestructura, connectivitat i seguretat de xarxa.",
                sys: "Sistemes operatius i entorns de treball.",
                cloud: "Infraestructura escalable i automatització.",
                dev: "Llenguatges i eines de desenvolupament.",
                db: "Gestió de dades massives i estructurades.",
                hw: "Suport de camp i entorns virtuals.",
                ia: "IA i optimització de fluxos amb n8n.",
                prod: "Gestió de projectes i col·laboració.",
                langs: "Comunicació en entorns globals."
            },
            items: {
                dns_desc: "Resolució i gestió de dominis",
                dhcp_desc: "IP dinàmica i gestió de subxarxes",
                pfsense_desc: "Fonaments de Firewall i Routing",
                cisco_desc: "Telèfons IP i Xarxes Bàsiques",
                grandstream_desc: "Suport de VoIP i Telefonia IP",
                wireshark_desc: "Anàlisi Bàsic de Paquets",
                linux_desc: "Admin de servidors i diagnòstic",
                windows_desc: "Servidors, AD i suport a usuaris",
                m365_desc: "Admin de Tenant i Apps Cloud",
                macos_desc: "Suport avançat i ús expert",
                mdm_desc: "Gestió de flotes iOS i Android",
                shell_desc: "Scripting Bàsic en Bash i PowerShell",
                azure_desc: "Fonaments d'Azure i Entra ID",
                aws_desc: "Conceptes Bàsics d'EC2 i S3",
                docker_desc: "Contenidors i Desplegaments Bàsics",
                k8s_desc: "Orquestració i escalat de clusters",
                terraform_desc: "Fonaments d'IaC",
                cloudflare_desc: "Seguretat WAF i rendiment DNS",
                python_desc: "Backend, Scripting i FastAPI",
                js_desc: "Frontend (React) i Lògica",
                react_desc: "Interfícies web modernes i SPA",
                fastapi_desc: "APIs d'alt rendiment amb Python",
                tailwind_desc: "Disseny web amb CSS modern",
                dotnet_desc: "C# i Aplicacions .NET Bàsiques",
                htmlcss_desc: "Maquetació i estils web",
                csharp_desc: "Aplicacions de consola i sistema",
                git_desc: "Control de versions i CI/CD",
                postgres_desc: "BD Relacional i Admin Bàsica",
                mysql_desc: "Gestió de BBDD Relacionals",
                sqlite_desc: "BBDD lleugera per a apps locals",
                mssql_desc: "Admin Bàsica de SQL Server",
                nosql_desc: "Gestió de documents JSON",
                zebra_desc: "Impressores Zebra i RFID especialista",
                honeywell_desc: "Suport maquinari industrial",
                igel_desc: "Thin Clients i Gestió Workspace",
                vmware_desc: "Entorns VMware i VirtualBox",
                vbox_desc: "Virtualització local avançada",
                rpi_desc: "Sistemes encastats i SBC",
                n8n_desc: "Automatització avançada de fluxos",
                copilot_desc: "Assistent IA per a codificació",
                gemini_desc: "Ús de LLMs per a productivitat",
                llm_desc: "GPT, Gemini i Prompt Engineering",
                teams_desc: "Col·laboració corporativa i Teams",
                office_desc: "Admin d'aplicacions Office 365",
                clickup_desc: "Gestió de tasques i projectes",
                notion_desc: "Espai de treball i documentació",
                jira_desc: "Gestió d'incidències i Agile",
                ansible_desc: "Gestió Bàsica de Configuració",
                vlan_desc: "Fonaments de Segmentació de Xarxa",
                ad_desc: "Gestió de dominis i usuaris AD",
                gpo_desc: "Polítiques de grup i seguretat",
                parallels_desc: "Virtualització a macOS",
                actions_desc: "Automatització de desplegaments",
                oracle_desc: "Fonaments d'Oracle DB",
                access_desc: "BBDD relacionals amb Office",
                json_desc: "Estructures de dades i APIs",
                rfid_desc: "Sistemes d'identificació per ràdio",
                peri_desc: "Suport a perifèrics i escàners",
                ollama_desc: "Execució de LLMs en local",
                prompt_desc: "Optimització de consultes a IA",
                excel_desc: "Excel i Gestió de Dades",
                project_desc: "Planificació Bàsica de Projectes",
                german_desc: "Coneixements inicials",
                agents_desc: "IA Agents i LangChain",
                vector_desc: "Bases de dades Vectorials",
                image_desc: "Generació d'imatges IA",
                redis_desc: "Conceptes Bàsics de Memòria Cau i BD en Memòria",
                diagnos_desc: "Diagnòstic avançat de HW",
                vite_desc: "Eines de frontend d'última generació",
                orm_desc: "Interaccions segures amb BBDD",
                sharp_desc: "Processament d'imatges",
                pages_desc: "Hosting estàtic d'alta disponibilitat",
                lighthouse_desc: "Optimització de SEO i rendiment",
                python_fastapi: "Python / FastAPI",
                python_fastapi_desc: "Scripting en Python i Backend Bàsic",
                js_react: "JavaScript / React",
                js_react_desc: "Frontend i Lògica Bàsica",
                cicd: "CI/CD & Automatització",
                cicd_desc: "GitHub Actions i Hosting d'alta disp.",
                sqlite_orm: "SQLite & SQLModel",
                sqlite_orm_desc: "BBDD locals i Mapeig ORM",
                zebra_rfid: "Zebra & RFID",
                zebra_rfid_desc: "Impressores industrials i Especialista RFID",
                honeywell_scan: "Escàners Honeywell",
                honeywell_scan_desc: "Escaneig industrial i Suport de Hardware",
                vminfra: "Infraestructura VM",
                vminfra_desc: "VMware ESXi i Operacions VirtualBox",
                hw_diag: "Suport HW & Diagnòstic",
                hw_diag_desc: "Perifèrics avançats i Resolució d'averies",
                claude_code: "Claude / Claude Code",
                claude_code_desc: "Raonament avançat i Eines CLI",
                openclaw: "OpenClaw",
                openclaw_desc: "Agents de IA Autònoms",
                nanobanana: "Nano Banana Pro",
                nanobanana_desc: "Generació d'Imatges Professional",
                openai_new: "OpenAI / GPT",
                openai_new_desc: "Ús de LLMs i Prompting",
                n8n_new: "Automatització n8n",
                n8n_new_desc: "Automatització Bàsica de Fluxos"
            }
        },
        projects: {
            p1_desc: "Portafoli inspirat en iOS26 amb HTML, CSS i JS. Mode fosc/claro, selector d'idioma i Dynamic Island com a navegació.",
            p2_desc: "Aplicació de gestió hotelera amb Python + PostgreSQL. Reserves, usuaris, seguretat, replicació i còpies de seguretat automàtiques.",
            p3_desc: "Joc d'acció amb tres tipus d'enemics i millores de personatge. Fet en Unity.",
            p4_desc: "Shooter 2D amb power-ups, sistema de puntuació i onades. Fet en Unity.",
            p5_desc: "Sistema TPV integral per a restaurants. Gestió de comandes en temps real, pantalla de cuina (KDS), tauler d'administració i desplegament automàtic. Amb Python (FastAPI), React i PostgreSQL.",
            p6_desc: "Carta digital estàtica d'alt rendiment sincronitzada amb el TPV local. Optimitzada per a mòbils (QR), SEO i càrrega instantània. Multiidioma i disseny responsive."
        },
        contact: { linkedin: "LinkedIn", email: "Email", github: "GitHub", whatsapp: "WhatsApp" },
        system: {
            cc: "Centre de Control",
            battery: "Bateria",
            charging: "Carregant",
            config_battery: "Configuració de la bateria...",
            wifi: "Wi-Fi",
            on: "Activat",
            known_networks: "Xarxes conegudes",
            wifi_settings: "Ajustos de Wi-Fi...",
            calendar: "Calendari",
            brightness: "Brillantor",
            fullscreen: "Pantalla completa",
            download_cv: "Descarregar CV",
            print_cv: "Imprimir CV",
            about_title: "Quant a aquest Portafoli",
            languages: "Idiomes",
            theme: "Tema",
            dark: "Fosc",
            light: "Clar",
            shortcuts_title: "Dreceres de Teclat",
            open_spotlight: "Obrir Spotlight",
            toggle_theme: "Toggle Tema",
            close_modals: "Tancar modals",
            nav_spotlight: "Navegar a Spotlight",
            select_result: "Seleccionar resultat",
            search_placeholder: "Cercar al portafoli...",
            dark_mode: "Mode Fosc",
            light_mode: "Mode Clar",
            suggestions: "Suggeriments",
            no_results: "Sense resultats",
            curr_pdf: "Currículum en PDF",
            date_settings: "Configuració de data i hora...",
            native: "Natiu / Bilingüe",
            prof_eng: "Competència professional",
            basic: "Coneixement bàsic",
            a1_level: "Nivell Inicial A1"
        },
        menubar: {
            apple_about: "Quant a aquest Portafoli",
            apple_pref: "Ajustos del Sistema...",
            file: "Arxiu",
            edit: "Edició",
            view: "Visualització",
            go: "Ves-hi",
            window: "Finestra",
            help: "Ajuda",
            copy_email: "Copiar Email",
            copy_link: "Copiar LinkedIn",
            copy_wa: "Copiar WhatsApp",
            shortcuts: "Atajos de Teclat",
            open_windows: "Finestres Obertes",
            send_email: "Enviar un Email"
        }
    },
    fr: {
        nav: { home: "Accueil", projects: "Projets", experience: "Expérience", skills: "Compétences", contact: "Contact" },
        hero: { title_prefix: "Salut, je suis", subtitle: "Spécialiste en assistance et administration informatique, avec une expérience dans les environnements d'entreprise et publics. Je gère les systèmes Linux et Windows, les réseaux, Microsoft 365, le matériel et les bases de données, en garantissant des opérations stables et efficaces. Je suis motivé par la résolution des incidents techniques et l'amélioration de l'expérience utilisateur." },
        cta: { view: "Voir les projets", cv: "Télécharger le CV" },
        sections: { exp: "Expérience", sk: "Compétences", proj: "Projets", contact: "Contact",
            exp_desc: "HIPRA · Ajuntament",
            sk_desc: "Réseaux · Cloud · Dev · IA",
            proj_desc: "Snack Tanger · ERAY · Hotel",
            contact_desc: "LinkedIn · Email · GitHub"
        },
        exp: {
            e1_place: "Juin 2025 - Présent", e1_role: "IT Workplace Intern",
            e1_t1: "Assistance technique de deuxième niveau (matériel, logiciels et connectivité).",
            e1_t2: "Gestion des incidents via Remedy et SmartIT.",
            e1_t3: "Préparation et déploiement d'équipements (ordinateurs portables, IGEL, périphériques).",
            e1_t4: "Configuration de mobiles iOS/Android, de téléphones Cisco et de scanners.",
            e1_t5: "Imprimantes RFID et thermiques (Zebra, Honeywell).",
            e1_t6: "Gestion des garanties et des réparations avec les fournisseurs.",
            e1_t7: "Collaboration en matière de sécurité, de correctifs et de mises à jour.",
            e2_place: "Nov 2023 – Avr 2024", e2_role: "IT Helpdesk Intern",
            e2_t1: "Assistance technique sur site et à distance pour le personnel municipal.",
            e2_t2: "Installation et maintenance des équipements et périphériques.",
            e2_t3: "Administration basique et gestion des permissions d'utilisateur.",
            e2_t4: "Outils Linux pour le diagnostic et la résolution des pannes.",
            e2_t5: "Documentation des procédures et guides d'utilisation.",
            e2_t6: "Préparation et déploiement d'équipements."
        },
        skills: {
            categories: {
                net: "Réseaux & Sécurité",
                sys: "Systèmes & Workspace",
                cloud: "Cloud & DevOps",
                dev: "Développement",
                db: "Bases de Données",
                hw: "Matériel & Support",
                ia: "IA & Automatisation",
                prod: "Productivité",
                langs: "Langues"
            },
            desc: {
                net: "Infrastructure, connectivité et sécurité réseau.",
                sys: "Systèmes d'exploitation et environnements de travail.",
                cloud: "Infrastructure évolutive et automatisation.",
                dev: "Langages et outils de développement.",
                db: "Gestion de données massives et structurées.",
                hw: "Support terrain et environnements virtuels.",
                ia: "IA et optimisation de flux avec n8n.",
                prod: "Gestion de projets et collaboration.",
                langs: "Communication dans des environnements mondiaux."
            },
            items: {
                dns_desc: "Résolution et gestion de domaines",
                dhcp_desc: "IP dynamique et gestion de sous-réseaux",
                pfsense_desc: "Fondamentaux Pare-feu et Routage",
                cisco_desc: "Téléphones IP et Réseaux de base",
                grandstream_desc: "Support VoIP et téléphonie IP",
                wireshark_desc: "Analyse basique de paquets",
                linux_desc: "Admin serveurs et diagnostic",
                windows_desc: "Serveurs, AD et support utilisateur",
                m365_desc: "Admin Tenant et Apps Cloud",
                macos_desc: "Support avancé et usage expert",
                mdm_desc: "Gestion de flottes iOS et Android",
                shell_desc: "Scripting de base en Bash et PowerShell",
                azure_desc: "Fondamentaux Azure et Entra ID",
                aws_desc: "Bases EC2 et S3",
                docker_desc: "Conteneurs et déploiements basiques",
                k8s_desc: "Orchestration et mise à l'échelle de clusters",
                terraform_desc: "Fondamentaux IaC",
                cloudflare_desc: "Sécurité WAF et performance DNS",
                python_desc: "Backend, Scripting et FastAPI",
                js_desc: "Frontend (React) et logique",
                react_desc: "Interfaces web modernes et SPAs",
                fastapi_desc: "APIs Python haute performance",
                tailwind_desc: "Conception web CSS moderne",
                dotnet_desc: "Applications C# et .NET de base",
                htmlcss_desc: "Mise en page et styles web",
                csharp_desc: "Applications console et système",
                git_desc: "Contrôle de version et CI/CD",
                postgres_desc: "BD relationnelle et admin de base",
                mysql_desc: "Gestion de BBDD relationnelles",
                sqlite_desc: "BBDD légère pour apps locales",
                mssql_desc: "Admin SQL Server de base",
                nosql_desc: "Gestion de documents JSON",
                zebra_desc: "Imprimantes Zebra et RFID spécialiste",
                honeywell_desc: "Support matériel industriel",
                igel_desc: "Clients légers et gestion de l'espace de travail",
                vmware_desc: "Environnements VMware et VirtualBox",
                vbox_desc: "Virtualisation locale avancée",
                rpi_desc: "Systèmes embarqués et SBC",
                n8n_desc: "Automatisation avancée des flux",
                copilot_desc: "Assistant de codage IA",
                gemini_desc: "Utilisation de LLM pour la productivité",
                llm_desc: "GPT, Gemini et Prompt Engineering",
                teams_desc: "Collaboration d'entreprise et Teams",
                office_desc: "Admin d'applications Office 365",
                clickup_desc: "Gestion de tâches et projets",
                notion_desc: "Espace de travail et documentation",
                jira_desc: "Gestion d'incidents et Agile",
                ansible_desc: "Gestion de configuration de base",
                vlan_desc: "Fondamentaux de segmentation réseau",
                ad_desc: "Gestion de domaines et d'utilisateurs AD",
                gpo_desc: "Stratégies de groupe et sécurité",
                parallels_desc: "Virtualisation sur macOS",
                actions_desc: "Automatisation des déploiements",
                oracle_desc: "Fondamentaux Oracle DB",
                access_desc: "BBDD relationnelles avec Office",
                json_desc: "Structures de données et APIs",
                rfid_desc: "Systèmes d'identification radio",
                peri_desc: "Support périphériques et scanners",
                ollama_desc: "Exécution de LLM en local",
                prompt_desc: "Optimisation des requêtes IA",
                excel_desc: "Excel et gestion de données",
                project_desc: "Planification de base de projets",
                german_desc: "Connaissances initiales",
                agents_desc: "Agents IA et LangChain",
                vector_desc: "Bases de données vectorielles",
                image_desc: "Génération d'images IA",
                redis_desc: "Bases de cache et BD en mémoire",
                diagnos_desc: "Diagnostic matériel avancé",
                vite_desc: "Outils frontend de nouvelle génération",
                orm_desc: "Interactions sécurisées avec les BBDD",
                sharp_desc: "Traitement d'images haute performance",
                pages_desc: "Hébergement statique haute disponibilité",
                lighthouse_desc: "Audit SEO et performance",
                python_fastapi: "Python / FastAPI",
                python_fastapi_desc: "Scripting Python et Backend de base",
                js_react: "JavaScript / React",
                js_react_desc: "Frontend et logique de base",
                cicd: "CI/CD & Automatisation",
                cicd_desc: "GitHub Actions et Hébergement haute disp.",
                sqlite_orm: "SQLite & SQLModel",
                sqlite_orm_desc: "BBDD locales et Cartographie ORM",
                zebra_rfid: "Zebra & RFID",
                zebra_rfid_desc: "Imprimantes industrielles et Spécialiste RFID",
                honeywell_scan: "Scanners Honeywell",
                honeywell_scan_desc: "Numérisation industrielle et Support Matériel",
                igel_new: "Clients Légers (IGEL)",
                igel_new_desc: "IGEL OS et Gestion de l'espace de travail",
                vminfra: "Infrastructure VM",
                vminfra_desc: "VMware ESXi et Opérations VirtualBox",
                hw_diag: "Support HW & Diagnostic",
                hw_diag_desc: "Périphériques avancés et Dépannage Matériel",
                n8n_new: "Automatisation n8n",
                n8n_new_desc: "Automatisation de flux de base",
                chatgpt_new: "ChatGPT",
                chatgpt_new_desc: "Expertise en Prompting et Analyse LLM",
                claude_new: "Claude / Claude Code",
                claude_new_desc: "Raisonnement avancé et Outils CLI",
                openclaw_new: "OpenClaw",
                openclaw_new_desc: "Agents d’IA Autonomes",
                nanobanana_new: "Nano Banana Pro",
                nanobanana_new_desc: "Génération d'Images Professionnelle",
                openai_new: "OpenAI / GPT",
                openai_new_desc: "Utilisation de LLM et Prompting"
            }
        },
        projects: {
            p1_desc: "Portfolio personnel inspiré de l'interface iOS26, développé avec HTML, CSS et JavaScript. Il présente l'expérience professionnelle, les compétences et les projets dans un design moderne et réactif. Il comprend un mode sombre/clair, une sélection de langue et une « Dynamic Island » interactive pour la navigation.",
            p2_desc: "Application complète pour la gestion intégrale d'une chaîne hôtelière. Elle comprend le contrôle des réservations, des clients, du personnel, des services et l'audit des données. Développée en Python (Tkinter) avec une base de données PostgreSQL, elle intègre la sécurité, la haute disponibilité, la réplication, les sauvegardes automatisées et les exportations en JSON/PDF.",
            p3_desc: "Jeu d'action se déroulant au XVIIIe siècle, mettant en scène ERAY, un personnage doté de pouvoirs magiques pour défendre son foyer. Il comprend trois types d'ennemis avec des attaques différentes et des objets qui améliorent les statistiques du joueur. Développé avec Unity, disponible en format exécutable gratuit.",
            p4_desc: "Jeu d'action en 2D développé avec Unity, dans lequel les joueurs contrôlent un vaisseau spatial qui doit affronter des vagues d'ennemis. Le jeu comprend des bonus et des améliorations pour le vaisseau, ainsi qu'un système de score basé sur la survie et la destruction des ennemis. Disponible en format exécutable gratuit.",
            p5_desc: "Système de point de vente complet pour les restaurants. Gestion des commandes en temps réel, écran de cuisine (KDS), tableau de bord d'administration et déploiement automatisé. Développé avec Python (FastAPI), React et PostgreSQL.",
            p6_desc: "Menu numérique statique haute performance synchronisé avec le point de vente local. Optimisé pour les mobiles (QR), le référencement et le chargement instantané. Multilingue et responsive design."
        },
        contact: { linkedin: "LinkedIn", email: "Email", github: "GitHub", whatsapp: "WhatsApp" },
        system: {
            cc: "Centre de Contrôle",
            battery: "Batterie",
            charging: "Chargement",
            config_battery: "Paramètres de la batterie...",
            wifi: "Wi-Fi",
            on: "Activé",
            known_networks: "Réseaux connus",
            wifi_settings: "Réglages Wi-Fi...",
            calendar: "Calendrier",
            brightness: "Luminosité",
            fullscreen: "Plein écran",
            download_cv: "Télécharger le CV",
            print_cv: "Imprimer le CV",
            about_title: "À propos de ce Portfolio",
            languages: "Langues",
            theme: "Thème",
            dark: "Sombre",
            light: "Clair",
            shortcuts_title: "Raccourcis Clavier",
            open_spotlight: "Ouvrir Spotlight",
            toggle_theme: "Changer le Thème",
            close_modals: "Fermer les modales",
            nav_spotlight: "Naviguer dans Spotlight",
            select_result: "Choisir le résultat",
            search_placeholder: "Rechercher dans le portfolio...",
            dark_mode: "Mode Sombre",
            light_mode: "Mode Clair",
            suggestions: "Suggestions",
            no_results: "Aucun résultat",
            curr_pdf: "Curriculum en PDF",
            main_section: "Section Principale",
            tpv_desc: "Système POS Intégral",
            date_settings: "Réglages Date et Heure...",
            native: "Maternel / Bilingue",
            prof_eng: "Compétence professionnelle",
            basic: "Connaissance de base",
            a1_level: "A1 Débutant"
        },
        menubar: {
            apple_about: "À propos de ce Portfolio",
            apple_pref: "Réglages Système...",
            file: "Fichier",
            edit: "Édition",
            view: "Présentation",
            go: "Aller",
            window: "Fenêtre",
            help: "Aide",
            copy_email: "Copier l'Email",
            copy_link: "Copier LinkedIn",
            copy_wa: "Copiar WhatsApp",
            shortcuts: "Raccourcis Clavier",
            open_windows: "Fenêtres Ouvertes",
            send_email: "Envoyer un Email"
        }
    },
    de: {
        nav: { home: "Startseite", projects: "Projekte", experience: "Erfahrung", skills: "Fähigkeiten", contact: "Kontakt" },
        hero: { title_prefix: "Hallo, ich bin", subtitle: "Spezialist für IT-Support und -Administration mit Erfahrung in Unternehmens- und öffentlichen Umgebungen. Ich verwalte Linux- und Windows-Systeme, Netzwerke, Microsoft 365, Hardware und Datenbanken und sorge für einen stabilen und effizienten Betrieb. Es motiviert mich, technische Probleme zu lösen und die Benutzererfahrung zu verbessern." },
        cta: { view: "Projekte ansehen", cv: "Lebenslauf herunterladen" },
        sections: { exp: "Erfahrung", sk: "Fähigkeiten", proj: "Projekte", contact: "Kontakt",
            exp_desc: "HIPRA · Ajuntament",
            sk_desc: "Netzwerk · Cloud · Dev · IA",
            proj_desc: "Snack Tanger · ERAY · Hotel",
            contact_desc: "LinkedIn · Email · GitHub"
        },
        exp: {
            e1_place: "Juni 2025 - Heute", e1_role: "IT Workplace Intern",
            e1_t1: "Technischer Support der Stufe 2 für Hardware, Software und Konnektivität.",
            e1_t2: "Vorfallmanagement mit Remedy / SmartIT.",
            e1_t3: "Vorbereitung und Bereitstellung von Geräten (Laptops, IGEL, Peripheriegeräte).",
            e1_t4: "Konfiguration von iOS/Android, Cisco-Telefonen und Scannern.",
            e1_t5: "RFID- und Thermodrucker (Zebra, Honeywell).",
            e1_t6: "Verwaltung von Garantien und Reparaturen mit Lieferanten.",
            e1_t7: "Zusammenarbeit bei Sicherheit, Patches und Updates.",
            e2_place: "Nov 2023 – Apr 2024", e2_role: "IT Helpdesk Intern",
            e2_t1: "Technischer Support vor Ort und per Fernzugriff für Mitarbeiter der Stadtverwaltung.",
            e2_t2: "Installation und Wartung von Geräten und Peripheriegeräten.",
            e2_t3: "Grundlegende Systemadministration und Benutzerberechtigungen.",
            e2_t4: "Linux-Tools zur Diagnose und Fehlerbehebung.",
            e2_t5: "Dokumentation von Verfahren und Benutzerhandbüchern.",
            e2_t6: "Vorbereitung und Bereitstellung von Geräten."
        },
        skills: {
            categories: {
                net: "Netztwerk & Sicherheit",
                sys: "Systeme & Workspace",
                cloud: "Cloud & DevOps",
                dev: "Entwicklung",
                db: "Datenbanken",
                hw: "Hardware & Support",
                ia: "KI & Automatisierung",
                prod: "Produktivität",
                langs: "Sprachen"
            },
            desc: {
                net: "Infrastruktur, Konnektivität und Netzwerksicherheit.",
                sys: "Betriebssystemadministration und Arbeitsumgebungen.",
                cloud: "Skalierbare Infrastruktur und Automatisierung.",
                dev: "Entwicklungssprachen und Tools.",
                db: "Big Data und strukturierte Datenverwaltung.",
                hw: "Außendienstunterstützung und virtuelle Umgebungen.",
                ia: "KI und Workflow-Optimierung mit n8n.",
                prod: "Projektmanagement und Zusammenarbeit.",
                langs: "Kommunikationsfähigkeit im globalen Umfeld."
            },
            items: {
                dns_desc: "Domain-Auflösung und -Verwaltung",
                dhcp_desc: "Dynamische IP und Subnetzverwaltung",
                pfsense_desc: "Grundlagen Firewall und Routing",
                cisco_desc: "IP-Telefone und Basisnetzwerke",
                grandstream_desc: "VoIP- und IP-Telefonie-Support",
                wireshark_desc: "Grundlegende Paketanalyse",
                linux_desc: "Serveradministration und Diagnose",
                windows_desc: "Server, AD und Benutzerunterstützung",
                m365_desc: "Tenant-Admin und Cloud-Apps",
                macos_desc: "Erweiterter Support und Expertennutzung",
                mdm_desc: "iOS- und Android-Flottenmanagement",
                shell_desc: "Grundlegendes Bash- und PowerShell-Scripting",
                azure_desc: "Grundlagen Azure und Entra ID",
                aws_desc: "Grundlagen EC2 und S3",
                docker_desc: "Container und grundlegende Bereitstellungen",
                k8s_desc: "Orchestrierung und Cluster-Skalierung",
                terraform_desc: "IaC-Grundlagen",
                cloudflare_desc: "WAF-Sicherheit and DNS-Performance",
                python_desc: "Backend, Scripting und FastAPI",
                js_desc: "Frontend (React) und Logik",
                react_desc: "Moderne Webschnittstellen und SPAs",
                fastapi_desc: "Hochleistungs-Python-APIs",
                tailwind_desc: "Modernes CSS-Webdesign",
                dotnet_desc: "Grundlegende C#- & .NET-Apps",
                htmlcss_desc: "Weblayout und Styling",
                csharp_desc: "Konsolen- und Systemanwendungen",
                git_desc: "Versionskontrolle und CI/CD",
                postgres_desc: "Relationale DB & Basic Admin",
                mysql_desc: "Relationales DB-Management",
                sqlite_desc: "Leichte DB für lokale Apps",
                mssql_desc: "Grundlegende SQL Server-Admin",
                nosql_desc: "JSON-Dokumentenverwaltung",
                zebra_desc: "Zebra-Drucker und RFID-Spezialist",
                honeywell_desc: "Hardware-Support für die Industrie",
                igel_desc: "Thin Clients und Workspace-Management",
                vmware_desc: "VMware- und VirtualBox-Umgebungen",
                vbox_desc: "Erweiterte lokale Virtualisierung",
                rpi_desc: "Embedded Systems und SBC",
                n8n_desc: "Erweiterte Workflow-Automatisierung",
                copilot_desc: "KI-gestützter Codierungsassistent",
                gemini_desc: "LLMs für die Produktivitätsnutzung",
                llm_desc: "GPT, Gemini und Prompt Engineering",
                teams_desc: "Unternehmenszusammenarbeit & Teams",
                office_desc: "Office 365 Enterprise-Admin",
                clickup_desc: "Aufgaben- und Projektmanagement",
                notion_desc: "Workspace und Dokumentation",
                jira_desc: "Fehlerverfolgung und Agile",
                ansible_desc: "Grundlegendes Konfigurationsmanagement",
                vlan_desc: "Grundlagen der Netzwerksegmentierung",
                ad_desc: "Domain- & Benutzerverwaltung (AD)",
                gpo_desc: "Gruppenrichtlinien & Sicherheit",
                parallels_desc: "macOS-Virtualisierung",
                actions_desc: "Bereitstellungsautomatisierung",
                oracle_desc: "Oracle DB Grundlagen",
                access_desc: "Relationale DBs mit Office",
                json_desc: "Datenstrukturen und APIs",
                rfid_desc: "Funkidentifikationssysteme",
                peri_desc: "Peripherie- und Scanner-Support",
                ollama_desc: "Lokale Ausführung von LLMs",
                prompt_desc: "KI-Abfrageoptimierung",
                excel_desc: "Excel & Datenmanagement",
                project_desc: "Grundlegende Projektplanung",
                german_desc: "Anfangskenntnisse",
                agents_desc: "KI-Agenten & LangChain",
                vector_desc: "Vektordatenbanken",
                image_desc: "KI-Bildgenerierung",
                redis_desc: "Cache & In-Memory-DB Grundlagen",
                diagnos_desc: "Fortgeschrittene HW-Diagnose",
                vite_desc: "Frontend-Tools der nächsten Generation",
                orm_desc: "Typsichere DB-Interaktionen",
                sharp_desc: "Hochleistungs-Bildverarbeitung",
                pages_desc: "Statische Hosting-Hochverfügbarkeit",
                lighthouse_desc: "SEO- und Leistungsoptimierung",
                python_fastapi: "Python / FastAPI",
                python_fastapi_desc: "Python Scripting & Basic Backend",
                js_react: "JavaScript / React",
                js_react_desc: "Frontend & grundlegende Logik",
                cicd: "CI/CD & Automatisierung",
                cicd_desc: "GitHub Actions & Hochverfügbares Hosting",
                sqlite_orm: "SQLite & SQLModel",
                sqlite_orm_desc: "Lokale BBDD & ORM-Mapping",
                zebra_rfid: "Zebra & RFID",
                zebra_rfid_desc: "Industrielle Drucker & RFID-Spezialist",
                honeywell_scan: "Honeywell Scanner",
                honeywell_scan_desc: "Industrielles Scannen & HW-Support",
                igel_new: "Thin Clients (IGEL)",
                igel_new_desc: "IGEL OS & Workspace-Management",
                vminfra: "VM-Infrastruktur",
                vminfra_desc: "VMware ESXi & VirtualBox Ops",
                hw_diag: "HW-Support & Diagnostik",
                hw_diag_desc: "Fortgeschrittene Peripheriegeräte & HW-Fehlerbehebung",
                n8n_new: "n8n-Automatisierung",
                n8n_new_desc: "Grundlegende Workflow-Automatisierung",
                chatgpt_new: "ChatGPT",
                chatgpt_new_desc: "Experten-LLM-Prompting & Analyse",
                claude_new: "Claude / Claude Code",
                claude_new_desc: "Fortgeschrittene Argumentation & CLI-Tools",
                openclaw_new: "OpenClaw",
                openclaw_new_desc: "Autonome KI-Agenten",
                nanobanana_new: "Nano Banana Pro",
                nanobanana_new_desc: "Professionelle Bilderzeugung",
                openai_new: "OpenAI / GPT",
                openai_new_desc: "LLM-Nutzung & Prompting"
            }
        },
        projects: {
            p1_desc: "Persönliches Portfolio, inspiriert von der Benutzeroberfläche von iOS26, entwickelt mit HTML, CSS und JavaScript. Präsentiert Berufserfahrung, Fähigkeiten und Projekte in einem modernen und responsiven Design. Enthält einen Dunkel-/Hellmodus, Sprachauswahl und eine interaktive “Dynamic Island“ für die Navigation.",
            p2_desc: "Anwendung zur umfassenden Verwaltung einer Hotelkette. Sie umfasst die Verwaltung von Buchungen, Gästen, Personal, Dienstleistungen und die Datenprüfung. Entwickelt in Python (Tkinter) mit einer PostgreSQL-Datenbank, integriert sie Sicherheit, hohe Verfügbarkeit, Replikation, automatisierte Backups und Exporte im JSON/PDF-Format.",
            p3_desc: "Action-Spiel, das im 18. Jahrhundert spielt und ERAY, einen Charakter mit magischen Kräften zur Verteidigung seines Heims, in den Mittelpunkt stellt. Es umfasst drei Arten von Feinden mit unterschiedlichen Angriffen und Objekten, die die Statistiken des Spielers verbessern. Entwickelt mit Unity, verfügbar im kostenlosen ausführbaren Format.",
            p4_desc: "2D-Action-Spiel, das mit Unity entwickelt wurde, in dem die Spieler ein Raumschiff steuern, das gegen Wellen von Feinden antreten muss. Das Spiel umfasst Boni und Verbesserungen für das Raumschiff sowie ein Punktesystem, das auf Überleben und Zerstörung von Feinden basiert. Verfügbar im kostenlosen ausführbaren Format.",
            p5_desc: "Umfassendes POS-System für Restaurants. Echtzeit-Bestellverwaltung, Küchendisplay-System (KDS), Admin-Dashboard und automatische Bereitstellung. Stack: Python (FastAPI), React und PostgreSQL.",
            p6_desc: "Hochleistungsfähiges statisches digitales Menü, das mit dem lokalen POS synchronisiert ist. Optimiert für Mobilgeräte (QR), SEO und sofortiges Laden. Mehrsprachiges und responsives Design."
        },
        contact: { linkedin: "LinkedIn", email: "E-Mail", github: "GitHub", whatsapp: "WhatsApp" },
        system: {
            cc: "Kontrollzentrum",
            battery: "Batterie",
            charging: "Laden",
            config_battery: "Batterieeinstellungen...",
            wifi: "Wi-Fi",
            on: "Ein",
            known_networks: "Bekannte Netzwerke",
            wifi_settings: "Wi-Fi-Einstellungen...",
            calendar: "Kalender",
            brightness: "Helligkeit",
            fullscreen: "Vollbild",
            download_cv: "Lebenslauf herunterladen",
            print_cv: "Lebenslauf drucken",
            about_title: "Über dieses Portfolio",
            languages: "Sprachen",
            theme: "Thema",
            dark: "Dunkel",
            light: "Hell",
            shortcuts_title: "Tastaturkürzel",
            open_spotlight: "Spotlight öffnen",
            toggle_theme: "Thema umschalten",
            close_modals: "Modale schließen",
            nav_spotlight: "In Spotlight navigieren",
            select_result: "Ergebnis auswählen",
            search_placeholder: "Im Portfolio suchen...",
            dark_mode: "Dunkelmodus",
            light_mode: "Hellmodus",
            suggestions: "Vorschläge",
            no_results: "Keine Ergebnisse",
            curr_pdf: "Lebenslauf als PDF",
            main_section: "Hauptbereich",
            tpv_desc: "Komplettes POS-System",
            date_settings: "Datum & Uhrzeit Einstellungen...",
            native: "Muttersprachlich / Bilingual",
            prof_eng: "Berufliche Kompetenz",
            basic: "Grundkenntnisse",
            a1_level: "A1 Anfänger"
        },
        menubar: {
            apple_about: "Über dieses Portfolio",
            apple_pref: "Systemeinstellungen...",
            file: "Ablage",
            edit: "Bearbeiten",
            view: "Darstellung",
            go: "Gehe zu",
            window: "Fenster",
            help: "Hilfe",
            copy_email: "E-Mail kopieren",
            copy_link: "LinkedIn kopieren",
            copy_wa: "WhatsApp kopieren",
            shortcuts: "Tastaturkurzbefehle",
            open_windows: "Offene Fenster",
            send_email: "E-Mail senden"
        }
    }
};
